-- Normalize Axel June 2026 task granularity without changing daily totals.
-- This keeps high-work days readable in /presenze: long repository-level
-- entries are split into operational sub-tasks with the same total minutes.

PRAGMA foreign_keys = ON;

INSERT INTO tasks (
  id, organization_id, project_id, assignee_member_id, title, description,
  status, priority, estimated_minutes, actual_minutes, due_at, created_at, updated_at,
  column_id, client_id, client_name, type, score, rich_description, assignee_name,
  tags_json, attachments_json, comments_json, sub_items_json, created_by_member_id,
  assignment_status, assignment_requested_by_member_id, assignment_requested_at, assignment_responded_at
)
VALUES
  (
    'task_axel_norm_20260614_optima_mcp_provider_setup',
    'org_demo_righello',
    'project_internal_optima',
    'mem_axel_wearerighello',
    '2026-06-14 - Optima MCP OAuth provider setup',
    'Setup provider MCP OAuth-first, redirect URI, scopes e configurazioni connector.',
    'done',
    'high',
    60,
    60,
    '2026-06-14T20:00:00.000Z',
    '2026-06-14T09:30:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'MCP OAuth',
    8,
    'Sottotask di normalizzazione da attivita GitHub verificata 14 giugno: provider setup, scopes, redirect URI e fallback API opzionale per connector MCP.',
    'Axel Fleureau',
    '["github-real","2026-06-14","normalizzazione","optima","mcp-oauth"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-14T09:30:00.000Z',
    '2026-06-14T20:00:00.000Z'
  ),
  (
    'task_axel_norm_20260614_optima_agent_panel',
    'org_demo_righello',
    'project_internal_optima',
    'mem_axel_wearerighello',
    '2026-06-14 - Optima pannello agenti MCP',
    'Pannello agenti, wizard setup e controlli UX per connector MCP.',
    'done',
    'high',
    60,
    60,
    '2026-06-14T20:00:00.000Z',
    '2026-06-14T10:30:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'Agent UI',
    8,
    'Sottotask di normalizzazione da attivita GitHub verificata 14 giugno: pannello agenti, wizard setup e controlli operativi MCP.',
    'Axel Fleureau',
    '["github-real","2026-06-14","normalizzazione","optima","agent-ui"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-14T10:30:00.000Z',
    '2026-06-14T20:00:00.000Z'
  ),
  (
    'task_axel_norm_20260622_obs_build_match_export',
    'org_demo_righello',
    'project_internal_obs_padel_stream_overlay',
    'mem_axel_wearerighello',
    '2026-06-22 - OBS build_match export end-to-end',
    'Build match, upload/download Mac agent e export finale mp4.',
    'done',
    'urgent',
    75,
    75,
    '2026-06-22T18:00:00.000Z',
    '2026-06-22T09:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'DaVinci pipeline',
    9,
    'Sottotask di normalizzazione da attivita GitHub verificata 22 giugno: build_match end-to-end, upload/download Mac agent e download finale mp4.',
    'Axel Fleureau',
    '["github-real","2026-06-22","normalizzazione","obs-padel","davinci"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-22T09:00:00.000Z',
    '2026-06-22T18:00:00.000Z'
  ),
  (
    'task_axel_norm_20260622_obs_overlay_marker_workflow',
    'org_demo_righello',
    'project_internal_obs_padel_stream_overlay',
    'mem_axel_wearerighello',
    '2026-06-22 - OBS overlay sponsor e marker workflow',
    'Sponsor overlay, marker badge, red card, overtime e quick markers.',
    'done',
    'high',
    45,
    45,
    '2026-06-22T18:00:00.000Z',
    '2026-06-22T11:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'Live production',
    8,
    'Sottotask di normalizzazione da attivita GitHub verificata 22 giugno: sponsor overlay, marker badge red card/overtime e quick markers.',
    'Axel Fleureau',
    '["github-real","2026-06-22","normalizzazione","obs-padel","overlay"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-22T11:00:00.000Z',
    '2026-06-22T18:00:00.000Z'
  ),
  (
    'task_axel_norm_20260623_obs_mac_agent_notarization',
    'org_demo_righello',
    'project_internal_obs_padel_stream_overlay',
    'mem_axel_wearerighello',
    '2026-06-23 - OBS Mac agent notarizzazione',
    'Packaging Mac agent, notarizzazione pkg, Gatekeeper e UI agent.',
    'done',
    'high',
    60,
    60,
    '2026-06-23T18:00:00.000Z',
    '2026-06-23T09:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'macOS agent',
    8,
    'Sottotask di normalizzazione da attivita GitHub verificata 23 giugno: packaging Mac agent, notarizzazione pkg, Gatekeeper e UI agent.',
    'Axel Fleureau',
    '["github-real","2026-06-23","normalizzazione","obs-padel","mac-agent"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-23T09:00:00.000Z',
    '2026-06-23T18:00:00.000Z'
  ),
  (
    'task_axel_norm_20260623_obs_operator_docs_tutorial',
    'org_demo_righello',
    'project_internal_obs_padel_stream_overlay',
    'mem_axel_wearerighello',
    '2026-06-23 - OBS operator checklist e tutorial PDF',
    'Hostinger docs, operator checklist, tutorial PDF e recovery marker card.',
    'done',
    'medium',
    30,
    30,
    '2026-06-23T18:00:00.000Z',
    '2026-06-23T11:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'Documentation',
    7,
    'Sottotask di normalizzazione da attivita GitHub verificata 23 giugno: Hostinger docs, operator checklist, tutorial PDF e recovery marker card.',
    'Axel Fleureau',
    '["github-real","2026-06-23","normalizzazione","obs-padel","docs"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-23T11:00:00.000Z',
    '2026-06-23T18:00:00.000Z'
  ),
  (
    'task_axel_norm_20260624_revolut_risk_engine_tests',
    'org_demo_righello',
    'project_internal_revolut_crypto_scalper',
    'mem_axel_wearerighello',
    '2026-06-24 - Revolut risk engine e test',
    'Risk engine, buy guards, position exits e test runtime.',
    'done',
    'high',
    60,
    60,
    '2026-06-24T18:00:00.000Z',
    '2026-06-24T09:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'Trading tests',
    8,
    'Sottotask di normalizzazione da attivita GitHub verificata 24 giugno: risk engine, buy guards, position exits e test runtime.',
    'Axel Fleureau',
    '["github-real","2026-06-24","normalizzazione","revolut","tests"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-24T09:00:00.000Z',
    '2026-06-24T18:00:00.000Z'
  ),
  (
    'task_axel_norm_20260624_revolut_exits_take_profit',
    'org_demo_righello',
    'project_internal_revolut_crypto_scalper',
    'mem_axel_wearerighello',
    '2026-06-24 - Revolut exits e take-profit tiers',
    'Ticker mapping, take-profit parziale, soft stop e cap buy giornaliero.',
    'done',
    'high',
    60,
    60,
    '2026-06-24T18:00:00.000Z',
    '2026-06-24T11:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'Trading exits',
    8,
    'Sottotask di normalizzazione da attivita GitHub verificata 24 giugno: ticker mapping, take-profit parziale, soft stop, stop loss e cap buy giornaliero.',
    'Axel Fleureau',
    '["github-real","2026-06-24","normalizzazione","revolut","exits"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-24T11:00:00.000Z',
    '2026-06-24T18:00:00.000Z'
  ),
  (
    'task_axel_norm_20260625_headroom_minimax_dashboard',
    'org_demo_righello',
    'project_internal_headroom',
    'mem_axel_wearerighello',
    '2026-06-25 - Headroom dashboard MiniMax',
    'Dashboard MiniMax, routing provider e fix streaming handler.',
    'done',
    'high',
    60,
    60,
    '2026-06-25T18:00:00.000Z',
    '2026-06-25T09:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'AI proxy dashboard',
    8,
    'Sottotask di normalizzazione da attivita GitHub verificata 25 giugno: dashboard MiniMax, routing provider e fix streaming handler.',
    'Axel Fleureau',
    '["github-real","2026-06-25","normalizzazione","headroom","minimax"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-25T09:00:00.000Z',
    '2026-06-25T18:00:00.000Z'
  ),
  (
    'task_axel_norm_20260625_headroom_pricing_savings',
    'org_demo_righello',
    'project_internal_headroom',
    'mem_axel_wearerighello',
    '2026-06-25 - Headroom pricing fallback e savings tracker',
    'Pricing fallback, savings tracker senza litellm e calcolo token/costi da log.',
    'done',
    'high',
    60,
    60,
    '2026-06-25T18:00:00.000Z',
    '2026-06-25T11:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'Cost tracking',
    8,
    'Sottotask di normalizzazione da attivita GitHub verificata 25 giugno: pricing fallback, savings tracker senza litellm e calcolo token/costi da log.',
    'Axel Fleureau',
    '["github-real","2026-06-25","normalizzazione","headroom","cost-tracking"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-25T11:00:00.000Z',
    '2026-06-25T18:00:00.000Z'
  ),
  (
    'task_axel_norm_20260627_revolut_cash_rich_probes',
    'org_demo_righello',
    'project_internal_revolut_crypto_scalper',
    'mem_axel_wearerighello',
    '2026-06-27 - Revolut cash-rich probes',
    'Cash-rich probes, relative strength probes e breakout continuation.',
    'done',
    'high',
    45,
    45,
    '2026-06-27T19:30:00.000Z',
    '2026-06-27T09:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'Trading probes',
    8,
    'Sottotask di normalizzazione da attivita GitHub verificata 27 giugno: cash-rich probes, relative strength probes e breakout continuation.',
    'Axel Fleureau',
    '["github-real","2026-06-27","normalizzazione","revolut","probes"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-27T09:00:00.000Z',
    '2026-06-27T19:30:00.000Z'
  ),
  (
    'task_axel_norm_20260627_revolut_buy_guards',
    'org_demo_righello',
    'project_internal_revolut_crypto_scalper',
    'mem_axel_wearerighello',
    '2026-06-27 - Revolut buy guards drawdown',
    'Guardie buy per drawdown, macro stress e simboli recentemente perdenti.',
    'done',
    'high',
    45,
    45,
    '2026-06-27T19:30:00.000Z',
    '2026-06-27T11:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'Risk guards',
    8,
    'Sottotask di normalizzazione da attivita GitHub verificata 27 giugno: guardie buy per drawdown, macro stress e simboli recentemente perdenti.',
    'Axel Fleureau',
    '["github-real","2026-06-27","normalizzazione","revolut","risk-guards"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-27T11:00:00.000Z',
    '2026-06-27T19:30:00.000Z'
  ),
  (
    'task_axel_norm_20260628_revolut_cost_basis_fills',
    'org_demo_righello',
    'project_internal_revolut_crypto_scalper',
    'mem_axel_wearerighello',
    '2026-06-28 - Revolut cost basis e fills',
    'Cost basis, fills, PnL realizzato e partial fills.',
    'done',
    'high',
    45,
    45,
    '2026-06-28T18:00:00.000Z',
    '2026-06-28T09:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'Trading accounting',
    8,
    'Sottotask di normalizzazione da attivita GitHub verificata 28 giugno: cost basis, fills, PnL realizzato e partial fills.',
    'Axel Fleureau',
    '["github-real","2026-06-28","normalizzazione","revolut","fills"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-28T09:00:00.000Z',
    '2026-06-28T18:00:00.000Z'
  ),
  (
    'task_axel_norm_20260628_revolut_wallet_positions',
    'org_demo_righello',
    'project_internal_revolut_crypto_scalper',
    'mem_axel_wearerighello',
    '2026-06-28 - Revolut posizioni wallet-backed',
    'Posizioni wallet-backed, pullback probes e retest lane.',
    'done',
    'high',
    45,
    45,
    '2026-06-28T18:00:00.000Z',
    '2026-06-28T11:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'Trading positions',
    8,
    'Sottotask di normalizzazione da attivita GitHub verificata 28 giugno: posizioni wallet-backed, pullback probes e retest lane.',
    'Axel Fleureau',
    '["github-real","2026-06-28","normalizzazione","revolut","positions"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-28T11:00:00.000Z',
    '2026-06-28T18:00:00.000Z'
  )
ON CONFLICT(id) DO UPDATE SET
  project_id = excluded.project_id,
  assignee_member_id = excluded.assignee_member_id,
  title = excluded.title,
  description = excluded.description,
  status = excluded.status,
  priority = excluded.priority,
  estimated_minutes = excluded.estimated_minutes,
  actual_minutes = excluded.actual_minutes,
  due_at = excluded.due_at,
  updated_at = CURRENT_TIMESTAMP,
  column_id = excluded.column_id,
  client_id = excluded.client_id,
  client_name = excluded.client_name,
  type = excluded.type,
  score = excluded.score,
  rich_description = excluded.rich_description,
  assignee_name = excluded.assignee_name,
  tags_json = excluded.tags_json,
  assignment_status = excluded.assignment_status,
  assignment_requested_by_member_id = excluded.assignment_requested_by_member_id,
  assignment_requested_at = excluded.assignment_requested_at,
  assignment_responded_at = excluded.assignment_responded_at;

UPDATE time_entries SET minutes = 120, updated_at = CURRENT_TIMESTAMP
WHERE id = 'time_axel_github_20260614_optima_mcp_setup_wizard'
  AND organization_id = 'org_demo_righello'
  AND member_id = 'mem_axel_wearerighello';

UPDATE time_entries SET minutes = 120, updated_at = CURRENT_TIMESTAMP
WHERE id = 'time_axel_github_20260622_obs_davinci_production_pipeline'
  AND organization_id = 'org_demo_righello'
  AND member_id = 'mem_axel_wearerighello';

UPDATE time_entries SET minutes = 90, updated_at = CURRENT_TIMESTAMP
WHERE id = 'time_axel_github_20260623_obs_davinci_production_pipeline'
  AND organization_id = 'org_demo_righello'
  AND member_id = 'mem_axel_wearerighello';

UPDATE time_entries SET minutes = 120, updated_at = CURRENT_TIMESTAMP
WHERE id = 'time_axel_github_20260624_revolut_trading_runtime'
  AND organization_id = 'org_demo_righello'
  AND member_id = 'mem_axel_wearerighello';

UPDATE time_entries SET minutes = 120, updated_at = CURRENT_TIMESTAMP
WHERE id = 'time_axel_github_20260625_headroom_minimax_proxy'
  AND organization_id = 'org_demo_righello'
  AND member_id = 'mem_axel_wearerighello';

UPDATE time_entries SET minutes = 120, updated_at = CURRENT_TIMESTAMP
WHERE id = 'time_axel_github_20260627_revolut_derisk_probe_runtime'
  AND organization_id = 'org_demo_righello'
  AND member_id = 'mem_axel_wearerighello';

UPDATE time_entries SET minutes = 90, updated_at = CURRENT_TIMESTAMP
WHERE id = 'time_axel_github_20260628_revolut_derisk_probe_runtime'
  AND organization_id = 'org_demo_righello'
  AND member_id = 'mem_axel_wearerighello';

INSERT INTO time_entries (
  id, organization_id, member_id, task_id, project_id, client_id, entry_date,
  minutes, billable, note, created_at, updated_at
)
VALUES
  ('time_axel_norm_20260614_optima_mcp_provider_setup', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_norm_20260614_optima_mcp_provider_setup', 'project_internal_optima', 'client_internal_righello_ops', '2026-06-14', 60, 1, 'Normalizzazione granularita: provider setup MCP OAuth, redirect URI e scopes.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_norm_20260614_optima_agent_panel', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_norm_20260614_optima_agent_panel', 'project_internal_optima', 'client_internal_righello_ops', '2026-06-14', 60, 1, 'Normalizzazione granularita: pannello agenti MCP e wizard setup.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_norm_20260622_obs_build_match_export', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_norm_20260622_obs_build_match_export', 'project_internal_obs_padel_stream_overlay', 'client_internal_righello_ops', '2026-06-22', 75, 1, 'Normalizzazione granularita: build_match, upload/download Mac agent e export mp4.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_norm_20260622_obs_overlay_marker_workflow', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_norm_20260622_obs_overlay_marker_workflow', 'project_internal_obs_padel_stream_overlay', 'client_internal_righello_ops', '2026-06-22', 45, 1, 'Normalizzazione granularita: overlay sponsor, marker badge e quick markers.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_norm_20260623_obs_mac_agent_notarization', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_norm_20260623_obs_mac_agent_notarization', 'project_internal_obs_padel_stream_overlay', 'client_internal_righello_ops', '2026-06-23', 60, 1, 'Normalizzazione granularita: packaging Mac agent, notarizzazione e Gatekeeper.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_norm_20260623_obs_operator_docs_tutorial', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_norm_20260623_obs_operator_docs_tutorial', 'project_internal_obs_padel_stream_overlay', 'client_internal_righello_ops', '2026-06-23', 30, 1, 'Normalizzazione granularita: operator checklist, tutorial PDF e recovery card.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_norm_20260624_revolut_risk_engine_tests', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_norm_20260624_revolut_risk_engine_tests', 'project_internal_revolut_crypto_scalper', 'client_internal_righello_ops', '2026-06-24', 60, 1, 'Normalizzazione granularita: risk engine, buy guards e test runtime.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_norm_20260624_revolut_exits_take_profit', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_norm_20260624_revolut_exits_take_profit', 'project_internal_revolut_crypto_scalper', 'client_internal_righello_ops', '2026-06-24', 60, 1, 'Normalizzazione granularita: exits, take-profit tiers, soft stop e caps.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_norm_20260625_headroom_minimax_dashboard', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_norm_20260625_headroom_minimax_dashboard', 'project_internal_headroom', 'client_internal_righello_ops', '2026-06-25', 60, 1, 'Normalizzazione granularita: dashboard MiniMax, routing provider e streaming handler.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_norm_20260625_headroom_pricing_savings', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_norm_20260625_headroom_pricing_savings', 'project_internal_headroom', 'client_internal_righello_ops', '2026-06-25', 60, 1, 'Normalizzazione granularita: pricing fallback, savings tracker e calcolo costi.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_norm_20260627_revolut_cash_rich_probes', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_norm_20260627_revolut_cash_rich_probes', 'project_internal_revolut_crypto_scalper', 'client_internal_righello_ops', '2026-06-27', 45, 1, 'Normalizzazione granularita: cash-rich probes e breakout continuation.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_norm_20260627_revolut_buy_guards', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_norm_20260627_revolut_buy_guards', 'project_internal_revolut_crypto_scalper', 'client_internal_righello_ops', '2026-06-27', 45, 1, 'Normalizzazione granularita: buy guards drawdown, macro stress e simboli perdenti.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_norm_20260628_revolut_cost_basis_fills', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_norm_20260628_revolut_cost_basis_fills', 'project_internal_revolut_crypto_scalper', 'client_internal_righello_ops', '2026-06-28', 45, 1, 'Normalizzazione granularita: cost basis, fills e PnL realizzato.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_norm_20260628_revolut_wallet_positions', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_norm_20260628_revolut_wallet_positions', 'project_internal_revolut_crypto_scalper', 'client_internal_righello_ops', '2026-06-28', 45, 1, 'Normalizzazione granularita: posizioni wallet-backed, pullback probes e retest lane.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
  member_id = excluded.member_id,
  task_id = excluded.task_id,
  project_id = excluded.project_id,
  client_id = excluded.client_id,
  entry_date = excluded.entry_date,
  minutes = excluded.minutes,
  billable = excluded.billable,
  note = excluded.note,
  updated_at = CURRENT_TIMESTAMP;

UPDATE tasks
SET actual_minutes = (
  SELECT COALESCE(SUM(time_entries.minutes), 0)
  FROM time_entries
  WHERE time_entries.organization_id = tasks.organization_id
    AND time_entries.task_id = tasks.id
),
updated_at = CURRENT_TIMESTAMP
WHERE organization_id = 'org_demo_righello'
  AND assignee_member_id = 'mem_axel_wearerighello'
  AND id IN (
    'task_axel_github_20260613_20260615_optima_mcp_setup_wizard',
    'task_axel_github_20260621_20260626_obs_davinci_production_pipeline',
    'task_axel_github_20260621_20260626_revolut_trading_runtime',
    'task_axel_github_20260621_20260626_headroom_minimax_proxy',
    'task_axel_github_20260626_20260630_revolut_derisk_probe_runtime',
    'task_axel_norm_20260614_optima_mcp_provider_setup',
    'task_axel_norm_20260614_optima_agent_panel',
    'task_axel_norm_20260622_obs_build_match_export',
    'task_axel_norm_20260622_obs_overlay_marker_workflow',
    'task_axel_norm_20260623_obs_mac_agent_notarization',
    'task_axel_norm_20260623_obs_operator_docs_tutorial',
    'task_axel_norm_20260624_revolut_risk_engine_tests',
    'task_axel_norm_20260624_revolut_exits_take_profit',
    'task_axel_norm_20260625_headroom_minimax_dashboard',
    'task_axel_norm_20260625_headroom_pricing_savings',
    'task_axel_norm_20260627_revolut_cash_rich_probes',
    'task_axel_norm_20260627_revolut_buy_guards',
    'task_axel_norm_20260628_revolut_cost_basis_fills',
    'task_axel_norm_20260628_revolut_wallet_positions'
  );
