-- Idempotent GitHub activity import for Axel Fleureau.
-- Period: 2026-06-04 17:56 Europe/Rome to 2026-06-06 08:36 Europe/Rome.
-- Source: verified GitHub activity across axelfleureau repositories.
-- Durations are intentionally not invented: actual_minutes stays 0 and tasks keep needs-duration.

UPDATE tasks
SET
  title = '2026-06-04/05 - Optima runner agentico, rapportini e PR operating layer',
  description = 'Implementato e stabilizzato il pacchetto runner agentico Optima: script Node, servizio VPS, env example, documentazione autenticazione Codex runner, heartbeat endpoint/UI, parser rapportini, heatmap presenze, fallback OpenAI runtime, preventivi/PDF e apertura PR #1 per il layer operativo agentico.',
  rich_description = 'Attivita GitHub verificata su axelfleureau/optima-beta. Periodo coperto: sera 4 giugno e giornata 5 giugno 2026. Include runner agentico, servizio VPS, endpoint heartbeat, elenco runner, migration database, UI agent jobs, import rapportini operativi, stabilizzazione heatmap presenze, scroll dialog preventivi AI, persistenza preventivi/output PDF, fallback OpenAI runtime e apertura PR #1 "[codex] Build Optima agentic operating layer". Nessuna durata inventata.',
  tags_json = '["github-real","2026-06-04","2026-06-05","task-update","needs-duration","optima-beta","agent-runner","vps-runner","heartbeat","rapportini","heatmap","quote-pdf","openai-runtime","pr-1"]',
  updated_at = CURRENT_TIMESTAMP
WHERE id = 'task_axel_github_20260604_20260605_optima_beta_runner_stability'
  AND organization_id = 'org_demo_righello';

UPDATE tasks
SET
  title = '2026-06-05 - Righello Site SEO locale, mobile UX e lockfile CI',
  description = 'Correzione clipping mobile nel submenu servizi, separazione landing SEO locali Pordenone/Mestre, rifinitura pagine SEO locali, collegamenti contestuali tra home/servizi/landing, rafforzamento pagine servizio per product SEO, workflow Search Console e riduzione boilerplate footer negli snippet. Criticita: CI/CD fallita per package-lock non sincronizzato.',
  rich_description = 'Attivita GitHub verificata su axelfleureau/righello-site. Include SEO locale Pordenone e Mestre, architettura contenuti, snippet search, Search Console workflow, mobile UX del submenu servizi e nota tecnica CI/CD: npm ci fallito per package.json/package-lock.json non sincronizzati, con drizzle-orm@0.45.2 e picomatch@4.0.4 mancanti nel lockfile. Nessuna durata inventata.',
  tags_json = '["github-real","2026-06-05","task-update","needs-duration","righello-site","seo-locale","search-console","mobile-ux","content-architecture","ci-cd","lockfile"]',
  updated_at = CURRENT_TIMESTAMP
WHERE id = 'task_axel_github_20260605_righello_site_push_updates'
  AND organization_id = 'org_demo_righello';

UPDATE tasks
SET
  title = '2026-06-06 - Optima PR #1 capability multi-tenant e control room agenti',
  description = 'Prosecuzione PR #1 Optima agentic operating layer: capability multi-tenant, MCP/OAuth, review room, ottimizzazione mobile control room agenti, integrazione Telegram/Hostinger runner e consolidamento heartbeat/stale errors.',
  rich_description = 'Attivita GitHub verificata su branch codex/pause-vps-runner, PR #1 "[codex] Build Optima agentic operating layer". Include capability registry multi-tenant, provider AI e MCP connector, review room, UI/UX mobile della pagina agenti, operational context, MCP auth/connectors, Telegram AI Assistant, Hostinger runner, heartbeat fresco durante job e gestione stale/offline. PR aperta, non ancora merge su main. Nessuna durata inventata.',
  tags_json = '["github-real","2026-06-06","task-update","needs-duration","optima-beta","pr-1","agentic-os","mcp","oauth","multi-tenant","telegram","hostinger","review-room","mobile-ux","heartbeat"]',
  updated_at = CURRENT_TIMESTAMP
WHERE id = 'task_axel_github_20260606_optima_beta_pause_vps_runner'
  AND organization_id = 'org_demo_righello';

INSERT OR IGNORE INTO tasks (
  id, organization_id, project_id, assignee_member_id, title, description,
  status, priority, estimated_minutes, actual_minutes, created_at, updated_at,
  column_id, client_id, client_name, type, score, rich_description,
  assignee_name, tags_json, attachments_json, comments_json, sub_items_json,
  created_by_member_id, assignment_status, assignment_requested_by_member_id,
  assignment_requested_at, assignment_responded_at
) VALUES
(
  'task_axel_github_20260604_portopiccolo_contacts_mail_backup',
  'org_demo_righello',
  'project_internal_portopiccolo',
  'mem_axel_wearerighello',
  '2026-06-04 sera - Portopiccolo export contatti mail e backup',
  'Tracciamento operativo esportazione contatti mail/webmail e controllo backup contatti.',
  'done',
  'medium',
  0,
  0,
  '2026-06-04T16:00:00.000Z',
  CURRENT_TIMESTAMP,
  'done',
  'client_rig_ppap',
  'Portopiccolo',
  'Operations / DNS email',
  7,
  'Attivita GitHub verificata su axelfleureau/Portopiccolo. Aree: DNS/networking, email, migrazione dominio e operations. Periodo: sera 4 giugno 2026. Nessuna durata inventata.',
  'Axel Fleureau',
  '["github-real","2026-06-04","needs-duration","portopiccolo","dns","email","domain-migration","contacts-backup"]',
  '[]',
  '[]',
  '[]',
  'mem_axel_wearerighello',
  'accepted',
  'mem_axel_wearerighello',
  '2026-06-04T16:00:00.000Z',
  '2026-06-04T16:00:00.000Z'
),
(
  'task_axel_github_20260604_revolut_kill_switch_derisk_guard',
  'org_demo_righello',
  'project_internal_revolut_crypto_scalper',
  'mem_axel_wearerighello',
  '2026-06-04 sera - Revolut kill switch derisk guardrails',
  'Rafforzamento kill switch con blocco delle vendite routinarie di derisk durante kill switch.',
  'done',
  'high',
  0,
  0,
  '2026-06-04T16:10:00.000Z',
  CURRENT_TIMESTAMP,
  'done',
  'client_internal_righello_ops',
  'Righello',
  'Backend / Risk management',
  8,
  'Attivita GitHub verificata su axelfleureau/revolut-crypto-scalper. Aree: backend, automazione trading, risk management e bugfix. Periodo: sera 4 giugno 2026. Nessuna durata inventata.',
  'Axel Fleureau',
  '["github-real","2026-06-04","needs-duration","revolut","kill-switch","derisk","risk-management","trading-automation"]',
  '[]',
  '[]',
  '[]',
  'mem_axel_wearerighello',
  'accepted',
  'mem_axel_wearerighello',
  '2026-06-04T16:10:00.000Z',
  '2026-06-04T16:10:00.000Z'
),
(
  'task_axel_github_20260605_revolut_recovery_supervisor',
  'org_demo_righello',
  'project_internal_revolut_crypto_scalper',
  'mem_axel_wearerighello',
  '2026-06-05 - Revolut recovery mode e supervisor deterministico',
  'Introduzione crash rebound recovery mode, supervised recovery-only mode, kill switch armato in recovery-only, supervisor agent deterministico, auto-resume supervisionato e test su risk engine, bot control, supervisor e worker loop.',
  'done',
  'high',
  0,
  0,
  '2026-06-05T08:30:00.000Z',
  CURRENT_TIMESTAMP,
  'done',
  'client_internal_righello_ops',
  'Righello',
  'Backend / AI supervisor',
  9,
  'Attivita GitHub verificata su axelfleureau/revolut-crypto-scalper. Aree: backend, AI/supervisor, automazione trading, recovery mode, risk management e testing. Nessuna durata inventata.',
  'Axel Fleureau',
  '["github-real","2026-06-05","needs-duration","revolut","recovery-mode","supervisor-agent","risk-management","testing","bot-control"]',
  '[]',
  '[]',
  '[]',
  'mem_axel_wearerighello',
  'accepted',
  'mem_axel_wearerighello',
  '2026-06-05T08:30:00.000Z',
  '2026-06-05T08:30:00.000Z'
),
(
  'task_axel_github_20260605_canale77_production_media_ingest',
  'org_demo_righello',
  'project_internal_canale77_ott_platform',
  'mem_axel_wearerighello',
  '2026-06-05 - Canale77 production readiness e media ingest',
  'Aggiunta link presentazione prodotto, documentazione stato arte, rotazione token admin, timestamp admin, sorgenti video ingest, hardening production readiness, intro streaming, webhook media ingest e aggiornamenti README/worker/server/manifest/privacy/sitemap/robots.',
  'done',
  'high',
  0,
  0,
  '2026-06-05T09:00:00.000Z',
  CURRENT_TIMESTAMP,
  'done',
  'client_internal_canale77',
  'Canale77',
  'Streaming / Cloudflare Worker',
  9,
  'Attivita GitHub verificata su axelfleureau/canale77-ott-platform. Aree: frontend, backend, streaming, media ingest, Cloudflare Worker, sicurezza, production readiness e documentazione. Nessuna durata inventata.',
  'Axel Fleureau',
  '["github-real","2026-06-05","needs-duration","canale77","ott-platform","streaming","media-ingest","cloudflare-worker","security","production-readiness"]',
  '[]',
  '[]',
  '[]',
  'mem_axel_wearerighello',
  'accepted',
  'mem_axel_wearerighello',
  '2026-06-05T09:00:00.000Z',
  '2026-06-05T09:00:00.000Z'
),
(
  'task_axel_github_20260605_tetha_agentic_email_worker',
  'org_demo_righello',
  'project_internal_tetha',
  'mem_axel_wearerighello',
  '2026-06-05 - Tetha cockpit agentico e worker email SendGrid',
  'Creazione cockpit agentic operations protetto, workflow email via SendGrid con draft/send/archive/policy, mappa servizi VPS e outbound Tetha agent worker queue con endpoint approve/claim/complete, auth agent, store email e worker Node.',
  'done',
  'high',
  0,
  0,
  '2026-06-05T10:00:00.000Z',
  CURRENT_TIMESTAMP,
  'done',
  'client_internal_righello_ops',
  'Righello',
  'AI operations / SendGrid',
  9,
  'Attivita GitHub verificata su axelfleureau/Tetha. Aree: AI operations, backend, SendGrid, worker VPS, automazioni e documentazione. Nessuna durata inventata.',
  'Axel Fleureau',
  '["github-real","2026-06-05","needs-duration","tetha","agentic-operations","sendgrid","worker-vps","email-workflow","automation"]',
  '[]',
  '[]',
  '[]',
  'mem_axel_wearerighello',
  'accepted',
  'mem_axel_wearerighello',
  '2026-06-05T10:00:00.000Z',
  '2026-06-05T10:00:00.000Z'
),
(
  'task_axel_github_20260605_solero_admin_ux_cms',
  'org_demo_righello',
  'project_internal_solero_sport_village',
  'mem_axel_wearerighello',
  '2026-06-05 - Solero dashboard admin UX e custom blocks',
  'Miglioramento gerarchia e contrasto dashboard admin, controlli ordinamento aree servizio, chiarimento flusso layout custom e pubblicazione discipline, correzione spaziatura template discoteca wide e miglioramento custom blocks admin.',
  'done',
  'medium',
  0,
  0,
  '2026-06-05T11:00:00.000Z',
  CURRENT_TIMESTAMP,
  'done',
  'client_rig_ssvo',
  'Solero Sport Village',
  'Frontend / Admin CMS',
  8,
  'Attivita GitHub verificata su axelfleureau/Solero-Sport-Village. Aree: frontend, admin CMS, UI/UX, bugfix e content management. Nessuna durata inventata.',
  'Axel Fleureau',
  '["github-real","2026-06-05","needs-duration","solero","admin-cms","ui-ux","custom-blocks","content-management"]',
  '[]',
  '[]',
  '[]',
  'mem_axel_wearerighello',
  'accepted',
  'mem_axel_wearerighello',
  '2026-06-05T11:00:00.000Z',
  '2026-06-05T11:00:00.000Z'
),
(
  'task_axel_github_20260605_buffr_app_store_availability',
  'org_demo_righello',
  'project_internal_buffr',
  'mem_axel_wearerighello',
  '2026-06-05 - BUFFR diagnosi disponibilita App Store',
  'Documentazione diagnosi disponibilita App Store e readiness tecnica release.',
  'done',
  'medium',
  0,
  0,
  '2026-06-05T11:30:00.000Z',
  CURRENT_TIMESTAMP,
  'done',
  'client_internal_righello_ops',
  'Righello',
  'Mobile / App Store',
  7,
  'Attivita GitHub verificata su axelfleureau/bufferello. Aree: mobile, App Store, documentazione tecnica e release readiness. Nessuna durata inventata.',
  'Axel Fleureau',
  '["github-real","2026-06-05","needs-duration","buffr","bufferello","app-store","release-readiness","mobile"]',
  '[]',
  '[]',
  '[]',
  'mem_axel_wearerighello',
  'accepted',
  'mem_axel_wearerighello',
  '2026-06-05T11:30:00.000Z',
  '2026-06-05T11:30:00.000Z'
),
(
  'task_axel_github_20260605_portopiccolo_dns_cloudflare_mail_migration',
  'org_demo_righello',
  'project_internal_portopiccolo',
  'mem_axel_wearerighello',
  '2026-06-05 - Portopiccolo DNS Cloudflare e migrazione mail',
  'Tracciamento nameserver dominio, readiness migrazione Cloudflare, stato DNS e backup mail, lezione domain transfer e monitoraggio orario migrazione.',
  'done',
  'medium',
  0,
  0,
  '2026-06-05T12:00:00.000Z',
  CURRENT_TIMESTAMP,
  'done',
  'client_rig_ppap',
  'Portopiccolo',
  'DNS / Cloudflare',
  8,
  'Attivita GitHub verificata su axelfleureau/Portopiccolo. Aree: DNS/networking, Cloudflare, email, dominio e operations. Nessuna durata inventata.',
  'Axel Fleureau',
  '["github-real","2026-06-05","needs-duration","portopiccolo","dns","cloudflare","email","domain-transfer","mail-backup"]',
  '[]',
  '[]',
  '[]',
  'mem_axel_wearerighello',
  'accepted',
  'mem_axel_wearerighello',
  '2026-06-05T12:00:00.000Z',
  '2026-06-05T12:00:00.000Z'
),
(
  'task_axel_github_20260605_obs_football_scorebug_ads',
  'org_demo_righello',
  'project_internal_obs_padel_stream_overlay',
  'mem_axel_wearerighello',
  '2026-06-05 - OBS football scorebug e cluster pubblicitari',
  'Aggiunta clock football e sostituzioni nella ref view, correzione seam scorebug football, controlli cluster pubblicitari nella control room e allineamento logo scorebug.',
  'done',
  'medium',
  0,
  0,
  '2026-06-05T13:00:00.000Z',
  CURRENT_TIMESTAMP,
  'done',
  'client_internal_righello_ops',
  'Righello',
  'Broadcast graphics',
  8,
  'Attivita GitHub verificata su axelfleureau/OBS-Padel-Stream-Overlay. Aree: frontend, broadcast graphics, regia live, UI/UX e football overlay. Nessuna durata inventata.',
  'Axel Fleureau',
  '["github-real","2026-06-05","needs-duration","obs-padel-stream-overlay","righello-live-studio","football","scorebug","ads-control-room","broadcast-graphics"]',
  '[]',
  '[]',
  '[]',
  'mem_axel_wearerighello',
  'accepted',
  'mem_axel_wearerighello',
  '2026-06-05T13:00:00.000Z',
  '2026-06-05T13:00:00.000Z'
),
(
  'task_axel_github_20260605_dico_brand_typography',
  'org_demo_righello',
  'project_internal_dico_online_site',
  'mem_axel_wearerighello',
  '2026-06-05 - DICO typography brand 4.0',
  'Rifinitura headline typography ed evoluzione typography brand DICO 4.0 su font, home, nav, footer e microinterazioni JS.',
  'done',
  'medium',
  0,
  0,
  '2026-06-05T14:00:00.000Z',
  CURRENT_TIMESTAMP,
  'done',
  'client_internal_dico_online',
  'DICO Online',
  'Frontend / Branding',
  7,
  'Attivita GitHub verificata su axelfleureau/Dico-online-site. Aree: frontend, branding, UI/UX e typography. Nessuna durata inventata.',
  'Axel Fleureau',
  '["github-real","2026-06-05","needs-duration","dico-online","branding","typography","frontend","microinteractions"]',
  '[]',
  '[]',
  '[]',
  'mem_axel_wearerighello',
  'accepted',
  'mem_axel_wearerighello',
  '2026-06-05T14:00:00.000Z',
  '2026-06-05T14:00:00.000Z'
),
(
  'task_axel_github_20260606_revolut_supervised_recovery_api',
  'org_demo_righello',
  'project_internal_revolut_crypto_scalper',
  'mem_axel_wearerighello',
  '2026-06-06 mattina - Revolut supervised recovery API e test',
  'Finalizzazione supervisor agent deterministico, auto-resume supervisionato in recovery e rafforzamento test/API bot control per gestione recovery supervisionata.',
  'done',
  'high',
  0,
  0,
  '2026-06-06T05:30:00.000Z',
  CURRENT_TIMESTAMP,
  'done',
  'client_internal_righello_ops',
  'Righello',
  'Backend / Recovery automation',
  9,
  'Attivita GitHub verificata su axelfleureau/revolut-crypto-scalper. Aree: backend, AI/supervisor, trading automation, recovery e testing. Periodo: mattina 6 giugno 2026. Nessuna durata inventata.',
  'Axel Fleureau',
  '["github-real","2026-06-06","needs-duration","revolut","supervised-recovery","supervisor-agent","bot-control-api","testing"]',
  '[]',
  '[]',
  '[]',
  'mem_axel_wearerighello',
  'accepted',
  'mem_axel_wearerighello',
  '2026-06-06T05:30:00.000Z',
  '2026-06-06T05:30:00.000Z'
);
