-- Idempotent GitHub activity import for Axel Fleureau.
-- Period: 2026-06-06 08:36 Europe/Rome to 2026-06-11 09:20 Europe/Rome.
-- Source: verified GitHub activity summary supplied by Axel.
-- Durations are estimated from verified GitHub activity breadth and project impact.
-- Time entries are created idempotently so workload and heatmap reflect the operational load.

INSERT INTO tasks (
  id, organization_id, project_id, assignee_member_id, title, description,
  status, priority, estimated_minutes, actual_minutes, due_at, created_at, updated_at,
  column_id, client_id, client_name, type, score, rich_description,
  assignee_name, tags_json, attachments_json, comments_json, sub_items_json,
  created_by_member_id, assignment_status, assignment_requested_by_member_id,
  assignment_requested_at, assignment_responded_at
)
VALUES
  (
    'task_axel_github_20260606_20260611_optima_agentic_os',
    'org_demo_righello',
    'project_internal_optima',
    'mem_axel_wearerighello',
    '2026-06-06/11 - Optima agentic OS, graph memory, Obsidian e preventivi',
    'Completamento PR #1 Optima e consolidamento layer agentico: graph memory, Graphify, import Hermes read-only, Obsidian-style workflow, MCP/OAuth readiness, AI assistant, UX mobile agenti, workload/presenze e preventivi/PDF.',
    'done',
    'urgent',
    1320,
    1320,
    '2026-06-11T07:20:00.000Z',
    '2026-06-06T06:36:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'AI operations / Agentic OS',
    10,
    'Attivita GitHub verificata su axelfleureau/optima-beta. Include merge PR #1 "[codex] Build Optima agentic operating layer", graph memory layer, bubble map e vista interattiva, Graphify come motore grafo, import Hermes read-only, import sicuro dati Hermes, collegamento know-how e skill Portopiccolo sync alla memoria grafo, trasformazione workflow stile Obsidian con canvas physics/vault actions, capability stack operativo, inbox polling AI assistant, runtime resolver modelli, hosted model routing framework, policy runtime nativa, confini multi-tenant, production readiness gate, readiness MCP/OAuth e service token, fallback business context/chat, correzioni overflow/scrolling mobile, control room agentica mobile, seed workload GitHub senza duplicati, heatmap presenze, task completati non tracciati, correzione durate/totali giugno, entry recovery Codex, banner task per giorno, operating model Righello per preventivi, creative system, creative kit Righello, import segnali Notion/Portopiccolo, persistenza preventivi, totali PDF, budget editabile, reset step budget, cover branding, chrome pagine interne PDF, link pubblici, storico preventivi Notion, auth preventivi, PDF legacy e variabili Wrangler/Cloudflare produzione. Durata stimata da ampiezza attivita GitHub e impatto operativo.',
    'Axel Fleureau',
    '["github-real","2026-06-06","2026-06-11","duration-estimated-github","optima-beta","agentic-os","mcp","oauth","graph-memory","graphify","hermes","obsidian","ai-assistant","presence","quotes","pdf","cloudflare","next-build"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-06T06:36:00.000Z',
    '2026-06-11T07:20:00.000Z'
  ),
  (
    'task_axel_github_20260606_20260611_portopiccolo_guesty_dns',
    'org_demo_righello',
    'project_internal_portopiccolo',
    'mem_axel_wearerighello',
    '2026-06-06/11 - Portopiccolo Guesty availability, booking fallback e DNS mail',
    'Rafforzamento flussi Guesty Open API/OAuth, availability calendario, fallback booking/catalogo, immagini listing, cache webhook e tracciamento migrazione DNS/mail Cloudflare/Zoho.',
    'done',
    'high',
    480,
    480,
    '2026-06-11T07:20:00.000Z',
    '2026-06-06T07:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_rig_ppap',
    'Portopiccolo',
    'Operations / Guesty DNS',
    9,
    'Attivita GitHub verificata su axelfleureau/Portopiccolo. Include OAuth Guesty Open API, query calendario, verifica availability prima dei risultati, fallback contro zero risultati, catalogo visibile se availability lenta, lock visuale risultati non disponibili, ripristino e hardening disponibilita calendario Guesty, fallback batch calendar availability, catalog fallback e immagini listing con preferenza gallery originali, hardening booking fallback, foundation webhook cache Guesty, fallback listing UI, shadow card dopo modale, Cloudflare nameserver cutover, Zoho DNS verification, Zoho MX cutover, DKIM, continuita DNS/mail, audit tenant Zoho e piano target Zoho EU. Workflow audit-images completato sui push rilevanti. Durata stimata da ampiezza attivita GitHub e impatto operativo.',
    'Axel Fleureau',
    '["github-real","2026-06-06","2026-06-11","duration-estimated-github","portopiccolo","guesty","availability","booking","webhook-cache","cloudflare","zoho","dns","mail"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-06T07:00:00.000Z',
    '2026-06-11T07:20:00.000Z'
  ),
  (
    'task_axel_github_20260606_20260611_righello_site_ai_grant_buffr',
    'org_demo_righello',
    'project_internal_righello_site',
    'mem_axel_wearerighello',
    '2026-06-06/11 - Righello Site AI grant, portfolio, BUFFR e performance mobile',
    'Landing AI grant, ottimizzazione motion/performance mobile, portfolio/progetti, pagina BUFFR, Cloudinary testimonial, layout mobile, case studies e nascondimento pagine incomplete.',
    'done',
    'high',
    600,
    600,
    '2026-06-11T07:20:00.000Z',
    '2026-06-06T08:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'Frontend / SEO Product',
    9,
    'Attivita GitHub verificata su axelfleureau/righello-site. Include landing AI grant con impostazione Righello, copy conversion-oriented, fonti ufficiali, stato apertura bando, countdown animato e scroll story; scroll momentum nativo, reveal motion disattivato su mobile, riduzione interferenze decorative; pagina portfolio/progetti e pagina prodotto BUFFR; CTA App Store, scroll scrub, canvas sprite e rendering demo; video testimonial Cloudinary e deduplicazione clienti testimonial; performance scroll generale, layout mobile servizi, visibilita loghi clienti su mobile; design upgrade case studies e hide pagine progetto incomplete. Criticita aperta: CI/CD fallita per npm ci, package.json/package-lock.json non sincronizzati, mancanti drizzle-orm@0.45.2 e picomatch@4.0.4 nel lockfile. Durata stimata da ampiezza attivita GitHub e impatto operativo.',
    'Axel Fleureau',
    '["github-real","2026-06-06","2026-06-11","duration-estimated-github","righello-site","ai-grant","buffr","portfolio","mobile-ux","performance","cloudinary","case-studies","ci-lockfile"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-06T08:00:00.000Z',
    '2026-06-11T07:20:00.000Z'
  ),
  (
    'task_axel_github_20260606_20260611_revolut_recovery_risk',
    'org_demo_righello',
    'project_internal_revolut_crypto_scalper',
    'mem_axel_wearerighello',
    '2026-06-06/11 - Revolut recovery scout, risk guards e sell floor',
    'Modalita speculative recovery scout, supervisor recovery, retention snapshot, riduzione microtransazioni, disabilitazione dust cleanup sells, scout buy tuning e guardrail su perdite.',
    'done',
    'high',
    360,
    360,
    '2026-06-11T07:20:00.000Z',
    '2026-06-06T08:30:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'Trading automation / Risk',
    9,
    'Attivita GitHub verificata su axelfleureau/revolut-crypto-scalper. Include speculative recovery scout, supervisor recovery action, bounding market snapshot retention, riduzione microtransazioni reali, disabilitazione automatic dust cleanup sells, ratchet winner scout buys, bypass cap cluster generico, bypass position cap, tuning soglia intraday, blocco buy con perdita cumulativa unrealized e enforcement di un real sell floor significativo. Durata stimata da ampiezza attivita GitHub e impatto operativo.',
    'Axel Fleureau',
    '["github-real","2026-06-06","2026-06-11","duration-estimated-github","revolut","recovery-scout","supervisor","risk-management","dust-sells","buy-guards","sell-floor"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-06T08:30:00.000Z',
    '2026-06-11T07:20:00.000Z'
  ),
  (
    'task_axel_github_20260606_20260611_tetha_agentic_document_workspace',
    'org_demo_righello',
    'project_internal_tetha',
    'mem_axel_wearerighello',
    '2026-06-06/11 - Tetha agentic document workspace e browser agents',
    'PR #1 per workspace documentale agentico, browser agent task queue, logging PDF, quote assistant, Codex CLI AI engine e document intelligence stores.',
    'done',
    'high',
    420,
    420,
    '2026-06-11T07:20:00.000Z',
    '2026-06-06T09:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'AI agents / Document intelligence',
    8,
    'Attivita GitHub verificata su axelfleureau/Tetha. Include PR #1 "[codex] add agentic document workspace", branch codex/agentic-document-workspace, workspace documentale agentico, browser agent task queue con claim/complete worker, logging errori generazione PDF preventivi, validazione ambiguita tecnica per quote assistant, chiarimento righe preventivo non prezzate, inferenza tecnica per membrana bituminosa nei preventivi tetti civili, Codex CLI AI engine, document intelligence, company knowledge store, browser task store, Codex CLI integration e documentazione dedicata. PR aperta non ancora mergeata. Durata stimata da ampiezza attivita GitHub e impatto operativo.',
    'Axel Fleureau',
    '["github-real","2026-06-06","2026-06-11","duration-estimated-github","tetha","agentic-document-workspace","browser-agent","quote-assistant","pdf-logging","codex-cli","document-intelligence","pr-1"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-06T09:00:00.000Z',
    '2026-06-11T07:20:00.000Z'
  ),
  (
    'task_axel_github_20260606_20260611_dico_webfolio_v2',
    'org_demo_righello',
    'project_internal_dico_online_site',
    'mem_axel_wearerighello',
    '2026-06-06/11 - DICO Webfolio v2 e branding template',
    'Creazione e iterazione DICO Webfolio/version 2, sostituzione con template Webfolio, branding DICO, imagery contestuale, artwork e spacing mobile.',
    'done',
    'medium',
    240,
    240,
    '2026-06-11T07:20:00.000Z',
    '2026-06-07T08:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_dico_online',
    'DICO Online',
    'Frontend / Branding',
    7,
    'Attivita GitHub verificata su axelfleureau/Dico-online-site. Include variante DICO Webfolio/version 2, rebuild come showcase concept, sostituzione con template Webfolio, applicazione branding DICO con logo/colori/bundle label/naming version link, imagery contestuale, message bubble fotografica, paper plane artwork, intro artwork mobile e spacing intro mobile. Durata stimata da ampiezza attivita GitHub e impatto operativo.',
    'Axel Fleureau',
    '["github-real","2026-06-07","2026-06-11","duration-estimated-github","dico-online-site","webfolio","branding","visual-design","mobile-spacing"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-07T08:00:00.000Z',
    '2026-06-11T07:20:00.000Z'
  ),
  (
    'task_axel_github_20260606_20260611_lumis_ios_photo_publisher',
    'org_demo_righello',
    'project_internal_lumis_photo_publisher',
    'mem_axel_wearerighello',
    '2026-06-06/11 - Lumis iOS camera validation, gallery e app icon',
    'Documentazione validazione camera iOS Lumis, miglioramento scroll timeline gallery e rifinitura app icon.',
    'done',
    'medium',
    90,
    90,
    '2026-06-11T07:20:00.000Z',
    '2026-06-08T08:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'iOS / UX branding',
    6,
    'Attivita GitHub verificata su axelfleureau/Photo-publisher-righello. Include documentazione validazione camera iOS Lumis, miglioramento scroll timeline gallery e rifinitura app icon Lumis iOS. Durata stimata da ampiezza attivita GitHub e impatto operativo.',
    'Axel Fleureau',
    '["github-real","2026-06-08","2026-06-11","duration-estimated-github","photo-publisher-righello","lumis","ios","camera-validation","gallery","app-icon"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-08T08:00:00.000Z',
    '2026-06-11T07:20:00.000Z'
  ),
  (
    'task_axel_github_20260606_20260611_reguta_agentic_ai_brain',
    'org_demo_righello',
    'project_internal_reguta_gest',
    'mem_axel_wearerighello',
    '2026-06-06/11 - Reguta Hermes-inspired agentic AI brain',
    'Branch codex/agentic-hermes-reguta con Reguta AI page, backend agentic brain, route agentiche, schema dati e documentazione architetturale.',
    'done',
    'high',
    270,
    270,
    '2026-06-11T07:20:00.000Z',
    '2026-06-09T08:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_rig_reca',
    'Reguta Cantina / Anselmi',
    'AI / Agentic architecture',
    8,
    'Attivita GitHub verificata su axelfleureau/Reguta-gest. Include creazione branch codex/agentic-hermes-reguta, Hermes-inspired Reguta AI brain, pagina Reguta AI, backend agentic brain, route agentiche, schema dati e documentazione architetturale. Branch creato, nessuna PR rilevata. Durata stimata da ampiezza attivita GitHub e impatto operativo.',
    'Axel Fleureau',
    '["github-real","2026-06-09","2026-06-11","duration-estimated-github","reguta-gest","hermes-inspired","agentic-ai","backend","frontend","architecture"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-09T08:00:00.000Z',
    '2026-06-11T07:20:00.000Z'
  )
ON CONFLICT(id) DO UPDATE SET
  project_id = excluded.project_id,
  assignee_member_id = excluded.assignee_member_id,
  title = excluded.title,
  description = excluded.description,
  status = excluded.status,
  priority = excluded.priority,
  estimated_minutes = excluded.estimated_minutes,
  actual_minutes = excluded.actual_minutes,
  due_at = excluded.due_at,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  column_id = excluded.column_id,
  client_id = excluded.client_id,
  client_name = excluded.client_name,
  type = excluded.type,
  score = excluded.score,
  rich_description = excluded.rich_description,
  assignee_name = excluded.assignee_name,
  tags_json = excluded.tags_json,
  attachments_json = excluded.attachments_json,
  comments_json = excluded.comments_json,
  sub_items_json = excluded.sub_items_json,
  created_by_member_id = excluded.created_by_member_id,
  assignment_status = excluded.assignment_status,
  assignment_requested_by_member_id = excluded.assignment_requested_by_member_id,
  assignment_requested_at = excluded.assignment_requested_at,
  assignment_responded_at = excluded.assignment_responded_at;

INSERT INTO time_entries (
  id, organization_id, member_id, task_id, project_id, client_id,
  entry_date, minutes, billable, note, created_at, updated_at
)
VALUES
  (
    'time_axel_github_20260606_20260611_optima_agentic_os',
    'org_demo_righello',
    'mem_axel_wearerighello',
    'task_axel_github_20260606_20260611_optima_agentic_os',
    'project_internal_optima',
    'client_internal_righello_ops',
    '2026-06-11',
    1320,
    1,
    'Stima GitHub 6-11 giugno: Optima agentic OS, graph memory/Graphify/Obsidian, MCP/OAuth, AI assistant, workload/presenze e preventivi/PDF.',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'time_axel_github_20260606_20260611_portopiccolo_guesty_dns',
    'org_demo_righello',
    'mem_axel_wearerighello',
    'task_axel_github_20260606_20260611_portopiccolo_guesty_dns',
    'project_internal_portopiccolo',
    'client_rig_ppap',
    '2026-06-11',
    480,
    1,
    'Stima GitHub 6-11 giugno: Guesty OAuth/Open API, availability, booking fallback, immagini listing, webhook cache e DNS/mail Cloudflare-Zoho.',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'time_axel_github_20260606_20260611_righello_site_ai_grant_buffr',
    'org_demo_righello',
    'mem_axel_wearerighello',
    'task_axel_github_20260606_20260611_righello_site_ai_grant_buffr',
    'project_internal_righello_site',
    'client_internal_righello_ops',
    '2026-06-11',
    600,
    1,
    'Stima GitHub 6-11 giugno: AI grant landing, portfolio/progetti, BUFFR page, performance mobile, Cloudinary testimonial e case studies.',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'time_axel_github_20260606_20260611_revolut_recovery_risk',
    'org_demo_righello',
    'mem_axel_wearerighello',
    'task_axel_github_20260606_20260611_revolut_recovery_risk',
    'project_internal_revolut_crypto_scalper',
    'client_internal_righello_ops',
    '2026-06-11',
    360,
    1,
    'Stima GitHub 6-11 giugno: recovery scout, supervisor recovery, retention, microtransaction reduction, dust sell block e risk guards.',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'time_axel_github_20260606_20260611_tetha_agentic_document_workspace',
    'org_demo_righello',
    'mem_axel_wearerighello',
    'task_axel_github_20260606_20260611_tetha_agentic_document_workspace',
    'project_internal_tetha',
    'client_internal_righello_ops',
    '2026-06-11',
    420,
    1,
    'Stima GitHub 6-11 giugno: agentic document workspace, browser agent queue, PDF quote logging, quote assistant e Codex CLI AI engine.',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'time_axel_github_20260606_20260611_dico_webfolio_v2',
    'org_demo_righello',
    'mem_axel_wearerighello',
    'task_axel_github_20260606_20260611_dico_webfolio_v2',
    'project_internal_dico_online_site',
    'client_internal_dico_online',
    '2026-06-11',
    240,
    1,
    'Stima GitHub 6-11 giugno: DICO Webfolio v2, template, branding, imagery, artwork e spacing mobile.',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'time_axel_github_20260606_20260611_lumis_ios_photo_publisher',
    'org_demo_righello',
    'mem_axel_wearerighello',
    'task_axel_github_20260606_20260611_lumis_ios_photo_publisher',
    'project_internal_lumis_photo_publisher',
    'client_internal_righello_ops',
    '2026-06-11',
    90,
    1,
    'Stima GitHub 6-11 giugno: validazione camera iOS Lumis, gallery timeline scroll e app icon.',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'time_axel_github_20260606_20260611_reguta_agentic_ai_brain',
    'org_demo_righello',
    'mem_axel_wearerighello',
    'task_axel_github_20260606_20260611_reguta_agentic_ai_brain',
    'project_internal_reguta_gest',
    'client_rig_reca',
    '2026-06-11',
    270,
    1,
    'Stima GitHub 6-11 giugno: branch agentic Hermes Reguta, AI page, backend brain, route agentiche, schema e documentazione.',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT(id) DO UPDATE SET
  task_id = excluded.task_id,
  project_id = excluded.project_id,
  client_id = excluded.client_id,
  entry_date = excluded.entry_date,
  minutes = excluded.minutes,
  billable = excluded.billable,
  note = excluded.note,
  updated_at = excluded.updated_at;
