-- Idempotent GitHub activity import for Axel Fleureau.
-- Period: 2026-06-12 07:20 Europe/Rome to 2026-06-12 20:22 Europe/Rome.
-- Source: verified GitHub activity summary supplied by Axel.
-- Workload policy: count the operational window conservatively as 12h net work,
-- added to the 2h already imported for early 2026-06-12, for a 14h CTO/founder day.

INSERT INTO tasks (
  id, organization_id, project_id, assignee_member_id, title, description,
  status, priority, estimated_minutes, actual_minutes, due_at, created_at, updated_at,
  column_id, client_id, client_name, type, score, rich_description,
  assignee_name, tags_json, attachments_json, comments_json, sub_items_json,
  created_by_member_id, assignment_status, assignment_requested_by_member_id,
  assignment_requested_at, assignment_responded_at
)
VALUES
  (
    'task_axel_github_20260612_gusto_table_vision_restaurant_os',
    'org_demo_righello',
    'project_internal_gusto_raffinato',
    'mem_axel_wearerighello',
    '2026-06-12 - Gusto Raffinato Restaurant OS e table vision realtime',
    'Evoluzione Restaurant OS con table vision realtime, backend Hermes/Hostinger, YOLO, OpenAI Vision, fallback Codex CLI, Flutter mobile e build iOS.',
    'done',
    'urgent',
    120,
    120,
    '2026-06-12T18:22:00.000Z',
    '2026-06-12T05:20:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_gusto_raffinato',
    'Gusto Raffinato',
    'Mobile / AI restaurant operations',
    10,
    'Attivita GitHub verificata su axelfleureau/gusto_raffinato. Include evoluzione modulo Restaurant OS con funzionalita real-time per table vision, gestione sala e lettura operativa tavoli; hardening backend Hermes/Hostinger per detector YOLO, fallback OpenAI Vision e fallback Codex CLI; modalita YOLO-only quando Vision non e disponibile; forzatura table vision remota TestFlight; rifinitura UI mobile Flutter per dashboard ristorante, Hermes OS, scanner table vision, feed, local UI e viste merchant; correzione scroll/clipping e miglioramento consumer/card specialita/dettaglio merchant; incremento build iOS.',
    'Axel Fleureau',
    '["github-real","2026-06-12","duration-estimated-github","gusto-raffinato","restaurant-os","table-vision","hermes","hostinger","yolo","openai-vision","codex-cli","flutter","testflight"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-12T05:20:00.000Z',
    '2026-06-12T18:22:00.000Z'
  ),
  (
    'task_axel_github_20260612_optima_agentic_readiness_github_mcp',
    'org_demo_righello',
    'project_internal_optima',
    'mem_axel_wearerighello',
    '2026-06-12 - Optima agentic readiness, GitHub MCP e self-improvement',
    'Rafforzamento architettura agentica Optima: graph links, recovery, readiness, self-improvement, GitHub MCP owner-scoped, Obsidian e task Axel.',
    'done',
    'urgent',
    135,
    135,
    '2026-06-12T18:22:00.000Z',
    '2026-06-12T05:45:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'AI operations / Optima OS',
    10,
    'Attivita GitHub verificata su axelfleureau/optima-beta. Include rafforzamento architettura agentica centrale con graph links, capacita agentiche, recovery e readiness production; rete di self-improvement agentico e seed attivazione produzione; integrazione GitHub MCP con configurazioni owner-scoped e approvazioni deploy limitate all owner; chiarimento readiness OAuth MCP e blocker agentici; monitoraggio job queue; azioni Obsidian Graph, setup provider e guida operativa; inserimento task GitHub Axel per 11-12 giugno.',
    'Axel Fleureau',
    '["github-real","2026-06-12","duration-estimated-github","optima-beta","agentic-os","mcp","github","owner-scoped","self-improvement","readiness","obsidian","graph-memory","cloudflare"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-12T05:45:00.000Z',
    '2026-06-12T18:22:00.000Z'
  ),
  (
    'task_axel_github_20260612_dico_frontend_brand_storytelling',
    'org_demo_righello',
    'project_internal_dico_online_site',
    'mem_axel_wearerighello',
    '2026-06-12 - DICO frontend, storytelling, asset ufficiali e performance',
    'Grande ciclo di rifinitura DICO: copy, storytelling, asset ufficiali, MEPA/SEND/PA, slider territoriale, mobile/desktop readability, performance e footer legale.',
    'done',
    'urgent',
    150,
    150,
    '2026-06-12T18:22:00.000Z',
    '2026-06-12T06:10:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_dico_online',
    'DICO Online',
    'Frontend / Brand system',
    10,
    'Attivita GitHub verificata su axelfleureau/Dico-online-site. Include riallineamento copy, storytelling, asset ufficiali e struttura narrativa; integrazione logo e asset DICO; revisione sezioni MEPA, SEND, comunicazione PA e proof nazionale; slider territoriale con contenuti, immagini, stemmi e stabilita; miglioramento leggibilita mobile/desktop, small text, contrasti, palette blu, bottoni rossi, footer legale; ottimizzazione scroll e slider con movimento automatico disattivato; selezione testo abilitata; correzione overflow footer e problemi visuali fra sezioni; documentazione onboarding, riallineamento committenza e audit diritti immagini.',
    'Axel Fleureau',
    '["github-real","2026-06-12","duration-estimated-github","dico-online","frontend","ui-ux","brand","storytelling","performance","seo","assets","slider","mobile"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-12T06:10:00.000Z',
    '2026-06-12T18:22:00.000Z'
  ),
  (
    'task_axel_github_20260612_revolut_scale_in_winners',
    'org_demo_righello',
    'project_internal_revolut_crypto_scalper',
    'mem_axel_wearerighello',
    '2026-06-12 - Revolut scale-in override su crypto winner',
    'Evoluzione logica trading per consentire scale-in sui winner dimostrati e test guardia acquisto.',
    'done',
    'high',
    60,
    60,
    '2026-06-12T18:22:00.000Z',
    '2026-06-12T07:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'Trading automation / Risk logic',
    8,
    'Attivita GitHub verificata su axelfleureau/revolut-crypto-scalper. Include evoluzione logica trading per consentire scale-in override sui winner gia dimostrati, rafforzamento strategia di pressione sui crypto winner invece di bloccare incrementi potenzialmente profittevoli e aggiornamento test di guardia acquisto per coprire il comportamento di scale-in.',
    'Axel Fleureau',
    '["github-real","2026-06-12","duration-estimated-github","revolut","trading","python","scale-in","winner","risk-management","tests"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-12T07:00:00.000Z',
    '2026-06-12T18:22:00.000Z'
  ),
  (
    'task_axel_github_20260612_canale77_realtime_ott_ux',
    'org_demo_righello',
    'project_internal_canale77_ott_platform',
    'mem_axel_wearerighello',
    '2026-06-12 - Canale77 targeting ingest, realtime catalogo e UX OTT',
    'Targeting ingest CalcioFVG, refresh realtime catalogo, esperienza OTT stile Netflix, navigazione TV remote, card/rail/tabs e boot loader.',
    'done',
    'high',
    90,
    90,
    '2026-06-12T18:22:00.000Z',
    '2026-06-12T07:30:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_canale77',
    'Canale77',
    'OTT / Realtime media UX',
    9,
    'Attivita GitHub verificata su axelfleureau/canale77-ott-platform. Include targeting ingest CalcioFVG, refresh realtime catalogo, esperienza OTT stile Netflix con hero playback, background preview, transizioni titolo e compact mode; navigazione TV remote e guardrail lunghezza testi; stabilizzazione card, rail scrolling, categoria tabs e card selezionate; riduzione tempi boot loader; aggiornamenti admin, server, worker e documentazione ingest/webhook/QA.',
    'Axel Fleureau',
    '["github-real","2026-06-12","duration-estimated-github","canale77","ott","calciofvg","realtime","worker","tv-remote","ux","performance"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-12T07:30:00.000Z',
    '2026-06-12T18:22:00.000Z'
  ),
  (
    'task_axel_github_20260612_lumis_public_seo_llms',
    'org_demo_righello',
    'project_internal_lumis_photo_publisher',
    'mem_axel_wearerighello',
    '2026-06-12 - Lumis SEO pubblico e llms.txt',
    'Miglioramento SEO pubblico Lumis, file llms.txt e metadata pubblici su route functions.',
    'done',
    'medium',
    60,
    60,
    '2026-06-12T18:22:00.000Z',
    '2026-06-12T08:00:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_internal_righello_ops',
    'Righello',
    'SEO / AI discoverability',
    7,
    'Attivita GitHub verificata su axelfleureau/Photo-publisher-righello. Include miglioramento SEO pubblico Lumis, aggiunta file llms.txt per esposizione e indicizzazione AI-oriented e aggiornamento route functions per metadata pubblici.',
    'Axel Fleureau',
    '["github-real","2026-06-12","duration-estimated-github","lumis","photo-publisher","seo","llms","cloudflare-functions","metadata"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-12T08:00:00.000Z',
    '2026-06-12T18:22:00.000Z'
  ),
  (
    'task_axel_github_20260612_portopiccolo_guesty_guest_area_pricing',
    'org_demo_righello',
    'project_internal_portopiccolo',
    'mem_axel_wearerighello',
    '2026-06-12 - Portopiccolo Guesty, area ospite, disponibilita e prezzi',
    'Area Ospite, errori booking, lookup/cache ospite, calendario annuale Guesty, prezzi date-specific, immagini e contenuti appartamento.',
    'done',
    'high',
    105,
    105,
    '2026-06-12T18:22:00.000Z',
    '2026-06-12T08:30:00.000Z',
    CURRENT_TIMESTAMP,
    'done',
    'client_rig_ppap',
    'Portopiccolo',
    'Booking / Guesty operations',
    9,
    'Attivita GitHub verificata su axelfleureau/Portopiccolo. Include miglioramento Area Ospite con errori booking, lookup ospite, cache verificata e migrazione cache reservation; ottimizzazione disponibilita e prezzi Guesty con calendario annuale reale, prezzi listing date-specific, arricchimento prezzi da calendari e parallelizzazione ricerche datate; preload immagini bento hero; rifinitura contenuti appartamento, fallback descrizione Maestrale e messaggistica disponibilita; stato caricamento calendario Guesty; logo Righello nel footer; operations log e workflow audit-images completato.',
    'Axel Fleureau',
    '["github-real","2026-06-12","duration-estimated-github","portopiccolo","guesty","area-ospite","booking","availability","pricing","cache","performance","audit-images"]',
    '[]',
    '[]',
    '[]',
    'mem_axel_wearerighello',
    'accepted',
    'mem_axel_wearerighello',
    '2026-06-12T08:30:00.000Z',
    '2026-06-12T18:22:00.000Z'
  )
ON CONFLICT(id) DO UPDATE SET
  project_id = excluded.project_id,
  assignee_member_id = excluded.assignee_member_id,
  title = excluded.title,
  description = excluded.description,
  status = excluded.status,
  priority = excluded.priority,
  estimated_minutes = excluded.estimated_minutes,
  actual_minutes = excluded.actual_minutes,
  due_at = excluded.due_at,
  updated_at = CURRENT_TIMESTAMP,
  column_id = excluded.column_id,
  client_id = excluded.client_id,
  client_name = excluded.client_name,
  type = excluded.type,
  score = excluded.score,
  rich_description = excluded.rich_description,
  assignee_name = excluded.assignee_name,
  tags_json = excluded.tags_json,
  attachments_json = excluded.attachments_json,
  comments_json = excluded.comments_json,
  sub_items_json = excluded.sub_items_json,
  created_by_member_id = excluded.created_by_member_id,
  assignment_status = excluded.assignment_status,
  assignment_requested_by_member_id = excluded.assignment_requested_by_member_id,
  assignment_requested_at = excluded.assignment_requested_at,
  assignment_responded_at = excluded.assignment_responded_at;

INSERT INTO time_entries (
  id, organization_id, member_id, task_id, project_id, client_id,
  entry_date, minutes, billable, note, created_at, updated_at
)
VALUES
  ('time_axel_github_20260612_gusto_table_vision_restaurant_os', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_github_20260612_gusto_table_vision_restaurant_os', 'project_internal_gusto_raffinato', 'client_internal_gusto_raffinato', '2026-06-12', 120, 1, 'Stima GitHub 12 giugno: Gusto Raffinato Restaurant OS, table vision realtime, Hermes/Hostinger, YOLO/OpenAI/Codex fallback e Flutter mobile.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_github_20260612_optima_agentic_readiness_github_mcp', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_github_20260612_optima_agentic_readiness_github_mcp', 'project_internal_optima', 'client_internal_righello_ops', '2026-06-12', 135, 1, 'Stima GitHub 12 giugno: Optima agentic readiness, GitHub MCP owner-scoped, recovery, queue monitor, Obsidian e self-improvement.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_github_20260612_dico_frontend_brand_storytelling', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_github_20260612_dico_frontend_brand_storytelling', 'project_internal_dico_online_site', 'client_internal_dico_online', '2026-06-12', 150, 1, 'Stima GitHub 12 giugno: DICO frontend/content/brand polish, asset ufficiali, PA proof, slider territoriale, mobile readability e performance.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_github_20260612_revolut_scale_in_winners', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_github_20260612_revolut_scale_in_winners', 'project_internal_revolut_crypto_scalper', 'client_internal_righello_ops', '2026-06-12', 60, 1, 'Stima GitHub 12 giugno: Revolut scale-in override su crypto winner e test buy guard.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_github_20260612_canale77_realtime_ott_ux', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_github_20260612_canale77_realtime_ott_ux', 'project_internal_canale77_ott_platform', 'client_internal_canale77', '2026-06-12', 90, 1, 'Stima GitHub 12 giugno: Canale77 CalcioFVG ingest, realtime catalogo, UX OTT Netflix-like, TV remote e boot loader.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_github_20260612_lumis_public_seo_llms', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_github_20260612_lumis_public_seo_llms', 'project_internal_lumis_photo_publisher', 'client_internal_righello_ops', '2026-06-12', 60, 1, 'Stima GitHub 12 giugno: Lumis SEO pubblico, llms.txt e metadata pubblici route functions.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('time_axel_github_20260612_portopiccolo_guesty_guest_area_pricing', 'org_demo_righello', 'mem_axel_wearerighello', 'task_axel_github_20260612_portopiccolo_guesty_guest_area_pricing', 'project_internal_portopiccolo', 'client_rig_ppap', '2026-06-12', 105, 1, 'Stima GitHub 12 giugno: Portopiccolo Area Ospite, Guesty availability/pricing, cache reservation, bento preload e operations log.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
  task_id = excluded.task_id,
  project_id = excluded.project_id,
  client_id = excluded.client_id,
  entry_date = excluded.entry_date,
  minutes = excluded.minutes,
  billable = excluded.billable,
  note = excluded.note,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO work_days (
  id, organization_id, member_id, entry_date, check_in_at, check_out_at, status, absence_reason, notes
)
VALUES
  (
    'workday_axel_20260612_github_import',
    'org_demo_righello',
    'mem_axel_wearerighello',
    '2026-06-12',
    '2026-06-12T05:20:00+02:00',
    '2026-06-12T20:22:00+02:00',
    'closed',
    NULL,
    'Presenza ricostruita da attivita GitHub verificata: 2h gia importate al mattino + 12h nette dal report 07:20-20:22, totale rapportini 14h. Finestra operativa ampia con pause non conteggiate come lavoro netto.'
  )
ON CONFLICT(organization_id, member_id, entry_date) DO UPDATE SET
  check_in_at = excluded.check_in_at,
  check_out_at = excluded.check_out_at,
  status = excluded.status,
  absence_reason = excluded.absence_reason,
  notes = excluded.notes,
  updated_at = CURRENT_TIMESTAMP;
