-- Import idempotente dei preventivi/proposte dalla sorgente Notion
-- "Richieste Documenti" indicata il 2026-06-09.
--
-- Fonte database:
-- https://app.notion.com/p/3d3f37c4ddc44e75abc438da6a8e532f
-- Data source: collection://c98b87db-7b9d-437c-89be-638e2bff88b4
--
-- Policy:
-- - questi record sono preventivi/proposte, non pagamenti o incassi;
-- - non scarica allegati, PDF, Drive o file esterni;
-- - email e dati sensibili non sono copiati nei raw_json;
-- - importi ricorrenti/varianti restano espliciti in note e snapshot.

INSERT INTO external_data_sources (
  id,
  organization_id,
  provider,
  source_type,
  external_id,
  title,
  url,
  domain,
  status,
  sync_mode,
  schema_json,
  allowed_fields_json,
  redacted_fields_json,
  last_synced_at,
  updated_at
) VALUES (
  'extsrc_notion_richieste_documenti',
  'org_demo_righello',
  'notion',
  'database',
  'collection://c98b87db-7b9d-437c-89be-638e2bff88b4',
  'Richieste Documenti',
  'https://app.notion.com/p/3d3f37c4ddc44e75abc438da6a8e532f',
  'quotes',
  'active',
  'manual_mcp_until_oauth',
  '{"title":"Titolo","documentTypes":["Preventivo","Proposta"],"purpose":"quote_request_and_historical_quote_memory"}',
  '["Titolo","Tipologia documento","Stato","Nome prospect / azienda (manuale)","Referente (manuale)","Settore (manuale)","Brief / Obiettivi (manuale)","Dati grezzi / Note (manuale)","Canali inclusi","Gamma Project URL","Rollup"]',
  '["Email (manuale)","PDF","Link Drive","attachments","phone","tax_id","secrets"]',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT(organization_id, provider, external_id) DO UPDATE SET
  title = excluded.title,
  url = excluded.url,
  domain = excluded.domain,
  status = excluded.status,
  sync_mode = excluded.sync_mode,
  schema_json = excluded.schema_json,
  allowed_fields_json = excluded.allowed_fields_json,
  redacted_fields_json = excluded.redacted_fields_json,
  last_synced_at = CURRENT_TIMESTAMP,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO quotes (
  id,
  organization_id,
  client_id,
  title,
  description,
  client_name,
  external_client_name,
  status,
  currency,
  total_cents,
  subtotal_cents,
  vat_cents,
  vat_rate,
  valid_until,
  items_json,
  voices_json,
  objectives_json,
  activities_json,
  terms_conditions,
  source_type,
  source_id,
  source_url,
  source_snapshot_json,
  created_at,
  updated_at
) VALUES
(
  'quote_notion_zeb_comunicazione_annuale_20260401',
  'org_demo_righello',
  NULL,
  'ZEB - piano comunicazione annuale',
  'Fonte Notion Richieste Documenti: gestione social, gestione ADS e shooting bimestrale. Canone 500 euro/mese + IVA per 12 mesi; shooting bimestrale separato 1.000 euro ogni 2 mesi + IVA. Non e prova di pagamento/incasso.',
  'ZEB',
  'ZEB',
  'draft',
  'EUR',
  600000,
  600000,
  132000,
  22,
  '2026-05-01T00:00:00.000Z',
  '[{"name":"Canone comunicazione annuale","description":"Gestione social, gestione ADS e coordinamento operativo per 12 mesi","quantity":12,"unitPrice":500,"total":6000}]',
  '[{"descrizione":"Gestione Social","quantita":12,"prezzoUnitario":200,"totale":2400,"categoria":"recurring","tipo":"monthly"},{"descrizione":"Gestione ADS","quantita":12,"prezzoUnitario":250,"totale":3000,"categoria":"recurring","tipo":"monthly"},{"descrizione":"Coordinamento operativo","quantita":12,"prezzoUnitario":50,"totale":600,"categoria":"recurring","tipo":"monthly"}]',
  '["Presenza social continuativa","Campagne Meta sempre attive","Valorizzazione territoriale e titolare"]',
  '["Pianificazione editoriale","Gestione campagne Meta","Shooting bimestrale separato"]',
  'Canone mensile anticipato; shooting fatturato separatamente ogni 2 mesi; budget adv a carico cliente.',
  'notion',
  'notion:page:e643b7ee-1ce7-4a48-bcb9-128b1c20e931',
  'https://app.notion.com/p/e643b7ee1ce74a48bcb9128b1c20e931',
  '{"sourceDatabase":"Richieste Documenti","sourceTitle":"Preventivo Comunicazione ZEB - Piano annuale 500 euro/mese","vatExcluded":true,"paymentProof":false,"recurringMonthlyCents":50000,"separateBimonthlyShootingCents":100000}',
  '2026-05-29T15:09:37.409Z',
  CURRENT_TIMESTAMP
),
(
  'quote_notion_rugby_udine_comunicazione_sito_20260424',
  'org_demo_righello',
  NULL,
  'Rugby Udine - sito, comunicazione e sponsorizzazione tecnica',
  'Fonte Notion Richieste Documenti: sito web, piano comunicazione stagionale e sponsorizzazione tecnica. Valore annuo progetto 22.800 euro + IVA; quota sponsor Righello 10.000 euro; costo effettivo Rugby Udine 12.800 euro + IVA. Non e prova di pagamento/incasso.',
  'Rugby Udine A.S.D.',
  'Rugby Udine A.S.D.',
  'draft',
  'EUR',
  1280000,
  1280000,
  281600,
  22,
  '2026-05-24T00:00:00.000Z',
  '[{"name":"Costo effettivo stagione Rugby Udine","description":"Sito, comunicazione e piano operativo dopo quota sponsor Righello","quantity":1,"unitPrice":12800,"total":12800}]',
  '[{"descrizione":"Formula mensile stagione","quantita":12,"prezzoUnitario":600,"totale":7200,"categoria":"recurring","tipo":"monthly"},{"descrizione":"Uscite contenuto indicative","quantita":10,"prezzoUnitario":100,"totale":1000,"categoria":"base","tipo":"one_time"},{"descrizione":"Sito web e impianto sponsor/comunicazione","quantita":1,"prezzoUnitario":4600,"totale":4600,"categoria":"base","tipo":"one_time"}]',
  '["Sito professionale e sponsor visibility","Narrativa 100 anni","Piano contenuti stagione 2025/2026"]',
  '["Architettura sito","Piano comunicazione 10 mesi","Shooting e contenuti stagionali"]',
  'Durata 12 mesi; compensazione minima sostenibile indicata nella fonte.',
  'notion',
  'notion:page:2bc8e490-b73d-47be-a596-8511858e3c84',
  'https://app.notion.com/p/2bc8e490b73d47bea5968511858e3c84',
  '{"sourceDatabase":"Richieste Documenti","sourceTitle":"Preventivo Rugby Udine A.S.D.","vatExcluded":true,"paymentProof":false,"annualProjectValueCents":2280000,"sponsorOffsetCents":1000000,"effectiveClientCostCents":1280000}',
  '2026-04-24T08:59:09.756Z',
  CURRENT_TIMESTAMP
),
(
  'quote_notion_bar_italia_shooting_adv_20260527',
  'org_demo_righello',
  NULL,
  'Bar Italia Lignano - shooting stagionale e ADV',
  'Fonte Notion Richieste Documenti: proposta A con shooting stagionale, 10 video verticali e gestione ADV. Shooting + 10 video 1.750 euro + IVA; gestione ADV 300 euro/mese + IVA; budget Meta separato. Non e prova di pagamento/incasso.',
  'Bar Italia - Lignano',
  'Bar Italia - Lignano',
  'draft',
  'EUR',
  175000,
  175000,
  38500,
  22,
  '2026-06-26T00:00:00.000Z',
  '[{"name":"Shooting stagionale e 10 video","description":"Una giornata completa di shooting, 10 video verticali IG Reels/ADV","quantity":1,"unitPrice":1750,"total":1750}]',
  '[{"descrizione":"Shooting stagionale + 10 video","quantita":1,"prezzoUnitario":1750,"totale":1750,"categoria":"base","tipo":"one_time"},{"descrizione":"Gestione ADV mensile","quantita":1,"prezzoUnitario":300,"totale":300,"categoria":"recurring","tipo":"monthly"}]',
  '["Presenza social stagionale","Contenuti video professionali","Campagne advertising dedicate"]',
  '["Shooting completo","Produzione Reels/ADV","Gestione Meta Ads"]',
  'Budget Meta consigliato circa 300 euro/mese a carico cliente; credito/buoni cena opzionale.',
  'notion',
  'notion:page:dba511bf-1609-44be-8eae-ce3a8f33459c#proposta-a',
  'https://app.notion.com/p/dba511bf160944be8eaece3a8f33459c',
  '{"sourceDatabase":"Richieste Documenti","sourceTitle":"Proposta commerciale Bar Italia","variant":"A","vatExcluded":true,"paymentProof":false,"monthlyAdvManagementCents":30000,"suggestedMediaSpendCents":30000}',
  '2026-05-27T16:28:18.172Z',
  CURRENT_TIMESTAMP
),
(
  'quote_notion_bar_italia_continuativo_20260527',
  'org_demo_righello',
  NULL,
  'Bar Italia Lignano - piano continuativo giugno-settembre',
  'Fonte Notion Richieste Documenti: proposta B continuativa giugno-settembre, 1 shooting mensile, 5 video, 1 grafica e gestione Meta Ads. Produzione 700 euro/mese + IVA; gestione ADV 300 euro/mese + IVA. Non e prova di pagamento/incasso.',
  'Bar Italia - Lignano',
  'Bar Italia - Lignano',
  'draft',
  'EUR',
  400000,
  400000,
  88000,
  22,
  '2026-06-26T00:00:00.000Z',
  '[{"name":"Piano continuativo estivo","description":"Produzione contenuti e gestione ADV per 4 mesi","quantity":4,"unitPrice":1000,"total":4000}]',
  '[{"descrizione":"Produzione contenuti mensile","quantita":4,"prezzoUnitario":700,"totale":2800,"categoria":"base","tipo":"monthly"},{"descrizione":"Gestione ADV mensile","quantita":4,"prezzoUnitario":300,"totale":1200,"categoria":"recurring","tipo":"monthly"}]',
  '["Continuita operativa estiva","Crescita riconoscibilita locale","Performance campagne"]',
  '["Shooting mensile","5 video mensili","1 contenuto grafico mensile","Gestione Meta Ads"]',
  'Budget Meta consigliato circa 300 euro/mese a carico cliente.',
  'notion',
  'notion:page:dba511bf-1609-44be-8eae-ce3a8f33459c#proposta-b',
  'https://app.notion.com/p/dba511bf160944be8eaece3a8f33459c',
  '{"sourceDatabase":"Richieste Documenti","sourceTitle":"Proposta commerciale Bar Italia","variant":"B","period":"Giugno-Settembre","vatExcluded":true,"paymentProof":false,"monthlyProductionCents":70000,"monthlyAdvManagementCents":30000,"suggestedMediaSpendCents":30000}',
  '2026-05-27T16:28:18.172Z',
  CURRENT_TIMESTAMP
),
(
  'quote_notion_hotel_michelangelo_site_cms_20260305',
  'org_demo_righello',
  NULL,
  'Hotel Michelangelo - sito CMS e booking engine',
  'Fonte Notion Richieste Documenti: rifacimento/ottimizzazione sito con CMS/back-end e integrazione Booking Engine/Channel Manager. Investimento 5.000 euro + IVA; pagamento 50% avvio, 50% consegna. Non e prova di pagamento/incasso.',
  'Hotel Michelangelo',
  'Hotel Michelangelo',
  'draft',
  'EUR',
  500000,
  500000,
  110000,
  22,
  '2026-03-19T00:00:00.000Z',
  '[{"name":"Sito + CMS + Booking Engine","description":"Analisi, UI/UX, sviluppo frontend, backend/CMS, integrazione booking, SEO base, test e pubblicazione","quantity":1,"unitPrice":5000,"total":5000}]',
  '[{"descrizione":"Sito mobile-first e UI/UX","quantita":1,"prezzoUnitario":1600,"totale":1600,"categoria":"base","tipo":"one_time"},{"descrizione":"Back-end/CMS e booking engine","quantita":1,"prezzoUnitario":2200,"totale":2200,"categoria":"base","tipo":"one_time"},{"descrizione":"SEO base, performance, test e go-live","quantita":1,"prezzoUnitario":1200,"totale":1200,"categoria":"base","tipo":"one_time"}]',
  '["Conversione prenotazioni","Performance e SEO base","Gestione contenuti scalabile"]',
  '["Sitemap e architettura","UI/UX responsive","CMS/back-end","Booking Engine","Go-live"]',
  'Opzioni: hosting gestito 240-400 euro/anno, manutenzione 150 euro/mese o 75 euro/ora, tracking avanzato da 250 euro.',
  'notion',
  'notion:page:61af5808-2f2d-4ffc-bdc4-ef984e73880c',
  'https://app.notion.com/p/61af58082f2d4ffcbdc4ef984e73880c',
  '{"sourceDatabase":"Richieste Documenti","sourceTitle":"Preventivo Hotel Michelangelo","vatExcluded":true,"paymentProof":false,"hostingAnnualRangeCents":[24000,40000],"maintenanceMonthlyCents":15000}',
  '2026-03-05T08:41:56.822Z',
  CURRENT_TIMESTAMP
),
(
  'quote_notion_portopiccolo_video_brand_film_20260325',
  'org_demo_righello',
  'client_rig_ppap',
  'Porto Piccolo Apartments - brand film esperienziale',
  'Fonte Notion Richieste Documenti: pacchetto A brand film esperienziale cinematografico con 2 giornate riprese, 3 operatori, asset library e revisioni. Totale 5.300 euro + IVA. Non e prova di pagamento/incasso.',
  'Portopiccolo Apartments',
  NULL,
  'draft',
  'EUR',
  530000,
  530000,
  116600,
  22,
  '2026-04-15T00:00:00.000Z',
  '[{"name":"Brand Film esperienziale","description":"Brand film 90-120 sec, 2 giornate, 3 operatori, asset library 4K","quantity":1,"unitPrice":5300,"total":5300}]',
  '[{"descrizione":"Pre-produzione e coordinamento","quantita":1,"prezzoUnitario":400,"totale":400,"categoria":"base","tipo":"one_time"},{"descrizione":"Produzione 2 giornate","quantita":1,"prezzoUnitario":2100,"totale":2100,"categoria":"base","tipo":"one_time"},{"descrizione":"Montaggio brand film e color grading","quantita":1,"prezzoUnitario":2400,"totale":2400,"categoria":"base","tipo":"one_time"},{"descrizione":"Musica, export e asset library","quantita":1,"prezzoUnitario":400,"totale":400,"categoria":"base","tipo":"one_time"}]',
  '["Posizionamento premium","Asset library 4K","Distribuzione commerciale"]',
  '["Pre-produzione","Riprese luxury","Montaggio e color","Export 4K"]',
  'Pagamento 40% firma, 40% inizio riprese, 20% consegna; validita 21 giorni.',
  'notion',
  'notion:page:150686c5-51e2-4df3-a146-e1299444bf73#pacchetto-a',
  'https://app.notion.com/p/150686c551e24df3a146e1299444bf73',
  '{"sourceDatabase":"Richieste Documenti","sourceTitle":"Preventivo Video Porto Piccolo Apartments","variant":"A","vatExcluded":true,"paymentProof":false}',
  '2026-03-25T17:20:57.398Z',
  CURRENT_TIMESTAMP
),
(
  'quote_notion_portopiccolo_video_brand_verticali_20260325',
  'org_demo_righello',
  'client_rig_ppap',
  'Porto Piccolo Apartments - brand film e 3 video verticali',
  'Fonte Notion Richieste Documenti: pacchetto B brand film + 3 video verticali POV, 3 giornate, asset library 40-50 clip. Totale 7.900 euro + IVA. Non e prova di pagamento/incasso.',
  'Portopiccolo Apartments',
  NULL,
  'draft',
  'EUR',
  790000,
  790000,
  173800,
  22,
  '2026-04-15T00:00:00.000Z',
  '[{"name":"Brand Film + 3 verticali","description":"Pacchetto A piu terza giornata e 3 video verticali 9:16","quantity":1,"unitPrice":7900,"total":7900}]',
  '[{"descrizione":"Tutto il Pacchetto A","quantita":1,"prezzoUnitario":5300,"totale":5300,"categoria":"base","tipo":"one_time"},{"descrizione":"Terza giornata riprese","quantita":1,"prezzoUnitario":750,"totale":750,"categoria":"base","tipo":"one_time"},{"descrizione":"Montaggio 3 verticali e color grading","quantita":1,"prezzoUnitario":1500,"totale":1500,"categoria":"base","tipo":"one_time"},{"descrizione":"Brani aggiuntivi ed export","quantita":1,"prezzoUnitario":350,"totale":350,"categoria":"base","tipo":"one_time"}]',
  '["Vertical-first ADV","Asset library premium","Contenuti per sito social e podcast"]',
  '["Brand film","3 video verticali","Asset library","Export social"]',
  'Opzioni: FPV drone +600 euro, quarta giornata +800 euro, adattamento EN +150 euro.',
  'notion',
  'notion:page:150686c5-51e2-4df3-a146-e1299444bf73#pacchetto-b',
  'https://app.notion.com/p/150686c551e24df3a146e1299444bf73',
  '{"sourceDatabase":"Richieste Documenti","sourceTitle":"Preventivo Video Porto Piccolo Apartments","variant":"B","vatExcluded":true,"paymentProof":false,"options":{"fpvDroneCents":60000,"extraDayCents":80000,"englishAdaptationCents":15000}}',
  '2026-03-25T17:20:57.398Z',
  CURRENT_TIMESTAMP
),
(
  'quote_notion_ca_barbieri_video_20260525',
  'org_demo_righello',
  NULL,
  'Ca Barbieri San Dona - video struttura con drone',
  'Fonte Notion Richieste Documenti: servizio video struttura interno + esterno + drone + zona bar. Totale imponibile 548 euro + IVA; foto integrative in omaggio. Non e prova di pagamento/incasso.',
  'Ca Barbieri San Dona',
  'Ca Barbieri San Dona',
  'draft',
  'EUR',
  54800,
  54800,
  12056,
  22,
  '2026-06-24T00:00:00.000Z',
  '[{"name":"Video struttura con drone","description":"Riprese interne, esterne, drone e zona bar; foto integrative omaggio","quantity":1,"unitPrice":548,"total":548}]',
  '[{"descrizione":"Servizio video struttura + drone + zona bar","quantita":1,"prezzoUnitario":548,"totale":548,"categoria":"base","tipo":"one_time"},{"descrizione":"Servizio fotografico integrativo omaggio","quantita":1,"prezzoUnitario":0,"totale":0,"categoria":"optional","tipo":"one_time"}]',
  '["Valorizzazione struttura ricettiva","Racconto ambienti e atmosfera","Consegna rapida"]',
  '["Riprese interne","Riprese esterne","Drone","Montaggio e color"]',
  'Consegna entro 96 ore lavorative; 1 giro revisione incluso; trasferta inclusa entro 50 km.',
  'notion',
  'notion:page:8f747c55-5fab-4fc5-8929-073d4f26c7f7',
  'https://app.notion.com/p/8f747c555fab4fc58929073d4f26c7f7',
  '{"sourceDatabase":"Richieste Documenti","sourceTitle":"Preventivo Ca Barbieri San Dona","vatExcluded":true,"vatIncludedCents":66856,"paymentProof":false,"giftPhotoValueCents":35000}',
  '2026-05-25T14:28:58.561Z',
  CURRENT_TIMESTAMP
),
(
  'quote_notion_video_torneo_live_20260415',
  'org_demo_righello',
  NULL,
  'Copertura video torneo - live principale',
  'Fonte Notion Richieste Documenti: copertura video torneo con 9 partite + finale. Proposta A: 1.800 euro + IVA finale mono o 1.900 euro + IVA finale multi. Non e prova di pagamento/incasso.',
  'Cliente torneo sportivo',
  'Cliente torneo sportivo',
  'draft',
  'EUR',
  190000,
  190000,
  41800,
  22,
  '2026-04-24T00:00:00.000Z',
  '[{"name":"Copertura live principale","description":"9 partite + finale con opzione finale multicamera","quantity":1,"unitPrice":1900,"total":1900}]',
  '[{"descrizione":"Gironi 9 partite live","quantita":9,"prezzoUnitario":180,"totale":1620,"categoria":"base","tipo":"one_time"},{"descrizione":"Finale multicamera","quantita":1,"prezzoUnitario":280,"totale":280,"categoria":"optional","tipo":"one_time"}]',
  '["Copertura evento sportivo","Stories in diretta","Produzione video campo"]',
  '["Operatore video","Riprese partite","Supporto live","Finale"]',
  'Vitto, alloggio e trasferte a carico cliente; singola location/giornata.',
  'notion',
  'notion:page:04f2a05c-dc0a-42e3-9701-932e3b36d90f#proposta-a',
  'https://app.notion.com/p/04f2a05cdc0a42e39701932e3b36d90f',
  '{"sourceDatabase":"Richieste Documenti","sourceTitle":"Copertura video torneo","variant":"A","vatExcluded":true,"paymentProof":false,"monoFinalTotalCents":180000,"multiFinalTotalCents":190000}',
  '2026-04-15T12:36:38.013Z',
  CURRENT_TIMESTAMP
),
(
  'quote_notion_video_torneo_completa_20260415',
  'org_demo_righello',
  NULL,
  'Copertura video torneo - live principale e seconda crew',
  'Fonte Notion Richieste Documenti: proposta A+B con live principale e copertura aggiuntiva di altre 9 partite in differita. Totale 3.150-3.250 euro + IVA; importato valore massimo 3.250 euro. Non e prova di pagamento/incasso.',
  'Cliente torneo sportivo',
  'Cliente torneo sportivo',
  'draft',
  'EUR',
  325000,
  325000,
  71500,
  22,
  '2026-04-24T00:00:00.000Z',
  '[{"name":"Copertura torneo completa","description":"Live principale + seconda crew in differita, valore massimo variante","quantity":1,"unitPrice":3250,"total":3250}]',
  '[{"descrizione":"Proposta A live principale","quantita":1,"prezzoUnitario":1900,"totale":1900,"categoria":"base","tipo":"one_time"},{"descrizione":"Copertura aggiuntiva 9 partite","quantita":9,"prezzoUnitario":150,"totale":1350,"categoria":"optional","tipo":"one_time"}]',
  '["Copertura completa torneo","Seconda crew","Produzione differita"]',
  '["Live principale","Riprese aggiuntive","Finale","Produzione non live"]',
  'Valore importato come massimo range A+B; vitto/alloggio/trasferte esclusi.',
  'notion',
  'notion:page:04f2a05c-dc0a-42e3-9701-932e3b36d90f#proposta-a-b',
  'https://app.notion.com/p/04f2a05cdc0a42e39701932e3b36d90f',
  '{"sourceDatabase":"Richieste Documenti","sourceTitle":"Copertura video torneo","variant":"A+B","vatExcluded":true,"paymentProof":false,"rangeCents":[315000,325000]}',
  '2026-04-15T12:36:38.013Z',
  CURRENT_TIMESTAMP
),
(
  'quote_notion_myo_frontend_premium_20260214',
  'org_demo_righello',
  NULL,
  'MYO Parrucchieri Mestre - sito front-end premium',
  'Fonte Notion Richieste Documenti: sito web mobile-first premium, custom code, SEO-ready, GA4/Search Console e CTA prenotazione. Proposta A 2.900 euro + IVA. Non e prova di pagamento/incasso.',
  'MYO Parrucchieri',
  'MYO Parrucchieri',
  'draft',
  'EUR',
  290000,
  290000,
  63800,
  22,
  '2026-03-15T00:00:00.000Z',
  '[{"name":"Sito front-end premium","description":"Sito custom mobile-first premium e SEO-ready","quantity":1,"unitPrice":2900,"total":2900}]',
  '[{"descrizione":"Front-end custom premium","quantita":1,"prezzoUnitario":1900,"totale":1900,"categoria":"base","tipo":"one_time"},{"descrizione":"SEO base, tracking e form/CTA","quantita":1,"prezzoUnitario":1000,"totale":1000,"categoria":"base","tipo":"one_time"}]',
  '["Comunicare valore","SEO locale","Percezione premium"]',
  '["Architettura pagine","Sviluppo custom","Tracking base","Form e CTA"]',
  'Pagamento consigliato 40% anticipo, 30% design approvato, 30% go-live.',
  'notion',
  'notion:page:d5b020ce-15de-4e5c-8b4e-d07399b5008d#proposta-a',
  'https://app.notion.com/p/d5b020ce15de4e5c8b4ed07399b5008d',
  '{"sourceDatabase":"Richieste Documenti","sourceTitle":"Preventivo Sito Web MYO Parrucchieri","variant":"A","vatExcluded":true,"paymentProof":false}',
  '2026-02-14T08:02:34.446Z',
  CURRENT_TIMESTAMP
),
(
  'quote_notion_myo_backend_dashboard_20260214',
  'org_demo_righello',
  NULL,
  'MYO Parrucchieri Mestre - sito e dashboard',
  'Fonte Notion Richieste Documenti: sito front-end + back-end/dashboard. Proposta B 4.500 euro + IVA. Non e prova di pagamento/incasso.',
  'MYO Parrucchieri',
  'MYO Parrucchieri',
  'draft',
  'EUR',
  450000,
  450000,
  99000,
  22,
  '2026-03-15T00:00:00.000Z',
  '[{"name":"Sito front-end + dashboard","description":"Sito custom premium con back-end/dashboard per gestione contenuti","quantity":1,"unitPrice":4500,"total":4500}]',
  '[{"descrizione":"Front-end custom premium","quantita":1,"prezzoUnitario":2900,"totale":2900,"categoria":"base","tipo":"one_time"},{"descrizione":"Back-end/Dashboard","quantita":1,"prezzoUnitario":1600,"totale":1600,"categoria":"base","tipo":"one_time"}]',
  '["Autorevolezza locale","Gestione autonoma contenuti","SEO e performance"]',
  '["Sviluppo sito","Dashboard contenuti","Tracking e go-live"]',
  'Pagamento consigliato 40% anticipo, 30% design approvato, 30% go-live.',
  'notion',
  'notion:page:d5b020ce-15de-4e5c-8b4e-d07399b5008d#proposta-b',
  'https://app.notion.com/p/d5b020ce15de4e5c8b4ed07399b5008d',
  '{"sourceDatabase":"Richieste Documenti","sourceTitle":"Preventivo Sito Web MYO Parrucchieri","variant":"B","vatExcluded":true,"paymentProof":false}',
  '2026-02-14T08:02:34.446Z',
  CURRENT_TIMESTAMP
)
ON CONFLICT(id) DO UPDATE SET
  client_id = excluded.client_id,
  title = excluded.title,
  description = excluded.description,
  client_name = excluded.client_name,
  external_client_name = excluded.external_client_name,
  status = excluded.status,
  currency = excluded.currency,
  total_cents = excluded.total_cents,
  subtotal_cents = excluded.subtotal_cents,
  vat_cents = excluded.vat_cents,
  vat_rate = excluded.vat_rate,
  valid_until = excluded.valid_until,
  items_json = excluded.items_json,
  voices_json = excluded.voices_json,
  objectives_json = excluded.objectives_json,
  activities_json = excluded.activities_json,
  terms_conditions = excluded.terms_conditions,
  source_type = excluded.source_type,
  source_id = excluded.source_id,
  source_url = excluded.source_url,
  source_snapshot_json = excluded.source_snapshot_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO external_data_records (
  id,
  organization_id,
  source_id,
  provider,
  record_type,
  external_id,
  external_url,
  title,
  summary,
  client_id,
  quote_id,
  occurred_at,
  amount_cents,
  currency,
  confidence,
  content_hash,
  raw_json,
  normalized_json,
  updated_at
)
SELECT
  'extrec_' || q.id,
  q.organization_id,
  'extsrc_notion_richieste_documenti',
  'notion',
  'quote',
  q.source_id,
  q.source_url,
  q.title,
  q.description,
  q.client_id,
  q.id,
  q.created_at,
  q.total_cents,
  q.currency,
  'extracted',
  'notion_richieste_documenti_' || q.id,
  '{"source":"Richieste Documenti","redacted":true,"paymentProof":false}',
  json_set(
    COALESCE(NULLIF(q.source_snapshot_json, ''), '{}'),
    '$.quoteId',
    q.id,
    '$.clientName',
    q.client_name,
    '$.amountCents',
    q.total_cents
  ),
  CURRENT_TIMESTAMP
FROM quotes q
WHERE q.organization_id = 'org_demo_righello'
  AND q.source_type = 'notion'
  AND q.source_id LIKE 'notion:page:%'
  AND q.id IN (
    'quote_notion_zeb_comunicazione_annuale_20260401',
    'quote_notion_rugby_udine_comunicazione_sito_20260424',
    'quote_notion_bar_italia_shooting_adv_20260527',
    'quote_notion_bar_italia_continuativo_20260527',
    'quote_notion_hotel_michelangelo_site_cms_20260305',
    'quote_notion_portopiccolo_video_brand_film_20260325',
    'quote_notion_portopiccolo_video_brand_verticali_20260325',
    'quote_notion_ca_barbieri_video_20260525',
    'quote_notion_video_torneo_live_20260415',
    'quote_notion_video_torneo_completa_20260415',
    'quote_notion_myo_frontend_premium_20260214',
    'quote_notion_myo_backend_dashboard_20260214'
  )
ON CONFLICT(organization_id, provider, external_id) DO UPDATE SET
  source_id = excluded.source_id,
  record_type = excluded.record_type,
  external_url = excluded.external_url,
  title = excluded.title,
  summary = excluded.summary,
  client_id = excluded.client_id,
  quote_id = excluded.quote_id,
  occurred_at = excluded.occurred_at,
  amount_cents = excluded.amount_cents,
  currency = excluded.currency,
  confidence = excluded.confidence,
  content_hash = excluded.content_hash,
  raw_json = excluded.raw_json,
  normalized_json = excluded.normalized_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO external_data_records (
  id,
  organization_id,
  source_id,
  provider,
  record_type,
  external_id,
  external_url,
  title,
  summary,
  occurred_at,
  currency,
  confidence,
  content_hash,
  raw_json,
  normalized_json,
  updated_at
) VALUES
(
  'extrec_notion_richieste_documenti_search_index_20260609',
  'org_demo_righello',
  'extsrc_notion_richieste_documenti',
  'notion',
  'quote',
  'notion:search:richieste-documenti:preventivo-proposta:2026-06-09',
  'https://app.notion.com/p/3d3f37c4ddc44e75abc438da6a8e532f',
  'Indice ricerca Notion Richieste Documenti - preventivi e proposte',
  'Search fallback del connettore Notion ha trovato almeno 25 pagine candidate. Import puntuale completato per 12 preventivi/varianti con importi certi; restano da verificare: ristorante, evento padel, Marcolin Covering, Fanna documentario, Pane e Bonta, 52 Gradi, Solero padel, Darinka, BUCUROSII, Farmacia Strazzolini, Il Giardino di Boschitt, L Esthetique e altri.',
  '2026-06-09T08:00:00.000Z',
  'EUR',
  'manual',
  'notion_richieste_documenti_search_index_20260609',
  '{"source":"Notion search","redacted":true}',
  '{"importedQuoteRows":12,"candidatePages":25,"queryToolIssue":"notion-query-data-sources not found","needsOauthImporter":true}',
  CURRENT_TIMESTAMP
)
ON CONFLICT(organization_id, provider, external_id) DO UPDATE SET
  title = excluded.title,
  summary = excluded.summary,
  raw_json = excluded.raw_json,
  normalized_json = excluded.normalized_json,
  updated_at = CURRENT_TIMESTAMP;
