-- Import Hermes Righello Client Intelligence into Optima operational memory.
-- Generated at 2026-06-15T10:53:30.489Z from /private/tmp/righello-client-intelligence-master.md.
-- Policy: read-only Hermes source; only the top client index is imported; contact fields, OneDrive references and attachments are excluded.

INSERT INTO external_data_sources (
  id,
  organization_id,
  provider,
  source_type,
  external_id,
  title,
  url,
  domain,
  status,
  sync_mode,
  schema_json,
  allowed_fields_json,
  redacted_fields_json,
  last_synced_at,
  updated_at
) VALUES (
  'extsrc_hermes_client_intelligence_master',
  'org_demo_righello',
  'hermes',
  'obsidian_markdown',
  'hermes:obsidian:righello-client-intelligence-master',
  'Hermes Righello Client Intelligence Master',
  NULL,
  'clients',
  'active',
  'manual_readonly_import',
  '{"source":"Hermes Righello Client Intelligence","file":"righello-client-intelligence-master.md","extractedFields":["code","name","status","invoiceCount","revenueCents","caseStudyPriority"],"excludedSections":["Schede Clienti dettagliate con recapiti"],"redaction":"Only top index table imported; phone/email/OneDrive fields ignored."}',
  '["code","name","status","invoiceCount","revenueCents","caseStudyPriority"]',
  '["email","telefono","phone","pec","partita_iva","onedrive","attachments","secrets"]',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
) ON CONFLICT(organization_id, provider, external_id) DO UPDATE SET
  title = excluded.title,
  domain = excluded.domain,
  status = excluded.status,
  sync_mode = excluded.sync_mode,
  schema_json = excluded.schema_json,
  allowed_fields_json = excluded.allowed_fields_json,
  redacted_fields_json = excluded.redacted_fields_json,
  last_synced_at = CURRENT_TIMESTAMP,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO clients (id, organization_id, name, email, company, status, created_at, updated_at)
VALUES
('client_hermes_3rtc', 'org_demo_righello', '3R-TECHNOLOGY DI MANZAN PAOLO', NULL, '3R-TECHNOLOGY DI MANZAN PAOLO', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_adsr', 'org_demo_righello', 'ADIMO S.R.L.', NULL, 'ADIMO S.R.L.', 'prospect', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_alsr', 'org_demo_righello', 'Alma S.r.l.', NULL, 'Alma S.r.l.', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_ardi', 'org_demo_righello', 'ArgisDistribution', NULL, 'ArgisDistribution', 'prospect', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_asdl', 'org_demo_righello', 'ASDL (ASD Dance Life)', NULL, 'ASDL (ASD Dance Life)', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_asso', 'org_demo_righello', 'Associazione Sportiva', NULL, 'Associazione Sportiva', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_atgr', 'org_demo_righello', 'ATHENA GROUP DI BISARO ROBERTO', NULL, 'ATHENA GROUP DI BISARO ROBERTO', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_blwh', 'org_demo_righello', 'BLACK AND WHITE SRLS', NULL, 'BLACK AND WHITE SRLS', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_busa', 'org_demo_righello', 'Busa Del Sauc', NULL, 'Busa Del Sauc', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_cana', 'org_demo_righello', 'Canale77', NULL, 'Canale77', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_clfa', 'org_demo_righello', 'Clara Falomo', NULL, 'Clara Falomo', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_colr', 'org_demo_righello', 'Comparin Lorena', NULL, 'Comparin Lorena', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_daen', 'org_demo_righello', 'Damia Entertainment', NULL, 'Damia Entertainment', 'inactive', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_dejo', 'org_demo_righello', 'DebeoJobs', NULL, 'DebeoJobs', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_internal_dico_online', 'org_demo_righello', 'DICO Online', NULL, 'DICO Online', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_elsr', 'org_demo_righello', 'Elite S.r.l.', NULL, 'Elite S.r.l.', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_enco', 'org_demo_righello', 'Ennevi Costruzioni srl', NULL, 'Ennevi Costruzioni srl', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_fanl', 'org_demo_righello', 'Fleureau Axel Nicolas Leon', NULL, 'Fleureau Axel Nicolas Leon', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_fiba', 'org_demo_righello', 'Fiba', NULL, 'Fiba', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_fipr', 'org_demo_righello', 'Friuli Innovazione Partner', NULL, 'Friuli Innovazione Partner', 'inactive', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_fium', 'org_demo_righello', 'FIUMEDICA SRL', NULL, 'FIUMEDICA SRL', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_friu', 'org_demo_righello', 'FriuliDoc', NULL, 'FriuliDoc', 'prospect', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_gden', 'org_demo_righello', 'Gruppo Distribuzione Energia Srl', NULL, 'Gruppo Distribuzione Energia Srl', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_gmam', 'org_demo_righello', 'GM Ambiente', NULL, 'GM Ambiente', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_idmi', 'org_demo_righello', 'Ippodromo di Merano', NULL, 'Ippodromo di Merano', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_lvlp', 'org_demo_righello', 'LVLP (Level Up)', NULL, 'LVLP (Level Up)', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_maro', 'org_demo_righello', 'MASCAZZINI ROBERTO', NULL, 'MASCAZZINI ROBERTO', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_maza', 'org_demo_righello', 'Broker Motors e Velvet motors', NULL, 'Broker Motors e Velvet motors', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_micc', 'org_demo_righello', 'Micco''s', NULL, 'Micco''s', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_naco', 'org_demo_righello', 'Nadia Costruzioni', NULL, 'Nadia Costruzioni', 'prospect', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_noic', 'org_demo_righello', 'NoiClub', NULL, 'NoiClub', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_nole', 'org_demo_righello', 'Noleggiobar', NULL, 'Noleggiobar', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_nume', 'org_demo_righello', 'Numerology', NULL, 'Numerology', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_paot', 'org_demo_righello', 'PapiOnTheBeach', NULL, 'PapiOnTheBeach', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_pnsp', 'org_demo_righello', 'PNL Sports', NULL, 'PNL Sports', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_poco', 'org_demo_righello', 'POLES COSTRUZIONI SRL', NULL, 'POLES COSTRUZIONI SRL', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_polv', 'org_demo_righello', 'Tenuta Polvaro s.a.s. di De Zan Caterina & C.', NULL, 'Tenuta Polvaro s.a.s. di De Zan Caterina & C.', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_rig_ppap', 'org_demo_righello', 'Portopiccolo Apartments', NULL, 'Portopiccolo Apartments', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_pusa', 'org_demo_righello', 'Punto Salute', NULL, 'Punto Salute', 'inactive', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_rbin', 'org_demo_righello', 'RB Interior', NULL, 'RB Interior', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_rig_reca', 'org_demo_righello', 'Reguta Cantina / Anselmi', NULL, 'Reguta Cantina / Anselmi', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_resr', 'org_demo_righello', 'Reginato s.r.l.', NULL, 'Reginato s.r.l.', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_ricg', 'org_demo_righello', 'Ricci group', NULL, 'Ricci group', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_rore', 'org_demo_righello', 'Roj''z Restaurant', NULL, 'Roj''z Restaurant', 'prospect', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_sisp', 'org_demo_righello', 'SCUOLA ITALIANA DI SCI PIANCAVALLO S.S.', NULL, 'SCUOLA ITALIANA DI SCI PIANCAVALLO S.S.', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_spes', 'org_demo_righello', 'Spesa', NULL, 'Spesa', 'prospect', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_rig_ssvo', 'org_demo_righello', 'APOLLO 2000 SRL (Solero Sport Village)', NULL, 'APOLLO 2000 SRL (Solero Sport Village)', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_stsa', 'org_demo_righello', 'Studio Sancassiani', NULL, 'Studio Sancassiani', 'prospect', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_sywe', 'org_demo_righello', 'Synergy Wellness', NULL, 'Synergy Wellness', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_tasr', 'org_demo_righello', 'Talentware S.r.l.', NULL, 'Talentware S.r.l.', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_tili', 'org_demo_righello', 'ThinkInk Lignano', NULL, 'ThinkInk Lignano', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_tmsl', 'org_demo_righello', 'Tomasella srl', NULL, 'Tomasella srl', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_tuco', 'org_demo_righello', 'Tubaro & Co', NULL, 'Tubaro & Co', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_vico', 'org_demo_righello', 'Vivila così', NULL, 'Vivila così', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_viva', 'org_demo_righello', 'VIVARADIO SRL', NULL, 'VIVARADIO SRL', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_vtsr', 'org_demo_righello', 'VRT SERVIZI SRL', NULL, 'VRT SERVIZI SRL', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('client_hermes_zasa', 'org_demo_righello', 'ZANUTTA SPA', NULL, 'ZANUTTA SPA', 'prospect', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  company = excluded.company,
  status = excluded.status,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO external_data_records (
  id,
  organization_id,
  source_id,
  provider,
  record_type,
  external_id,
  external_url,
  title,
  summary,
  client_id,
  project_id,
  task_id,
  quote_id,
  interaction_id,
  occurred_at,
  amount_cents,
  currency,
  confidence,
  content_hash,
  raw_json,
  normalized_json,
  created_at,
  updated_at
) VALUES
(
  'extrec_hermes_client_3rtc',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:3RTC',
  NULL,
  '3R-TECHNOLOGY DI MANZAN PAOLO - scheda cliente Hermes',
  'Cliente 3R-TECHNOLOGY DI MANZAN PAOLO: stato Attivo, 3 fatture tracciate, fatturato aggregato 1950,00 €. Fonte Hermes read-only.',
  'client_hermes_3rtc',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  195000,
  'EUR',
  'extracted',
  '5be81f26cf1f635a6f5a82e27e9401438f70845d89f1bd08501938cbcdcd0f4b',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"3RTC","status":"Attivo","invoiceCount":3,"revenueCents":195000,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_adsr',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:ADSR',
  NULL,
  'ADIMO S.R.L. - scheda cliente Hermes',
  'Cliente ADIMO S.R.L.: stato Prospect, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_adsr',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '105532adad93dae7d39d4e1f6678d461412354ec128b5702e5c9a3b95cc36925',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"ADSR","status":"Prospect","invoiceCount":0,"revenueCents":0,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"C"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_alsr',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:ALSR',
  NULL,
  'Alma S.r.l. - scheda cliente Hermes',
  'Cliente Alma S.r.l.: stato Attivo, 1 fatture tracciate, fatturato aggregato 199,00 €. Fonte Hermes read-only.',
  'client_hermes_alsr',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  19900,
  'EUR',
  'extracted',
  'bc45601326e926815bf261ba392bce882960623708b156dc60cb12525787ef9f',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"ALSR","status":"Attivo","invoiceCount":1,"revenueCents":19900,"hasDocx":true,"hasNarrative":true,"hasOrganic":true,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_ardi',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:ARDI',
  NULL,
  'ArgisDistribution - scheda cliente Hermes',
  'Cliente ArgisDistribution: stato Prospect, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_ardi',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  'c10ead242791b7911406d6289b5441e708fcc5acd1a31932140d1c6eb1a1b952',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"ARDI","status":"Prospect","invoiceCount":0,"revenueCents":0,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"C"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_asdl',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:ASDL',
  NULL,
  'ASDL (ASD Dance Life) - scheda cliente Hermes',
  'Cliente ASDL (ASD Dance Life): stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_asdl',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '3420a43b24cc4f2fed2ef30cc18817db54f8e2ddc039c649d2ee7e36a4955e02',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"ASDL","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":true,"hasNarrative":true,"hasOrganic":true,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_asso',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:ASSO',
  NULL,
  'Associazione Sportiva - scheda cliente Hermes',
  'Cliente Associazione Sportiva: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_asso',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '28fa6c31e8908fe845280d51e5d05051f05b5d8d22f89c6026c805f7d42f4a42',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"ASSO","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_atgr',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:ATGR',
  NULL,
  'ATHENA GROUP DI BISARO ROBERTO - scheda cliente Hermes',
  'Cliente ATHENA GROUP DI BISARO ROBERTO: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_atgr',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '6fa81cda83e435b34572ffc15d6f9f29d7641e820a05a156b07778da5f500564',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"ATGR","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_blwh',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:BLWH',
  NULL,
  'BLACK AND WHITE SRLS - scheda cliente Hermes',
  'Cliente BLACK AND WHITE SRLS: stato Attivo, 7 fatture tracciate, fatturato aggregato 2732,30 €. Fonte Hermes read-only.',
  'client_hermes_blwh',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  273230,
  'EUR',
  'extracted',
  'ff6b4506e7f408b506e66251c6516f27d457a943d87c64092c4978d6837a3f83',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"BLWH","status":"Attivo","invoiceCount":7,"revenueCents":273230,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_busa',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:BUSA',
  NULL,
  'Busa Del Sauc - scheda cliente Hermes',
  'Cliente Busa Del Sauc: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_busa',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '6c07eb9aedf6e317b2f02763816c19a2443c74dbe20d870e068db5b9db26f04e',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"BUSA","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_cana',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:CANA',
  NULL,
  'Canale77 - scheda cliente Hermes',
  'Cliente Canale77: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_cana',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '40ea0109d059e86ac4a5eec5cfc22439842862858d7b34f092cd7a922c44c2c9',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"CANA","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_clfa',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:CLFA',
  NULL,
  'Clara Falomo - scheda cliente Hermes',
  'Cliente Clara Falomo: stato Attivo, 1 fatture tracciate, fatturato aggregato 872,00 €. Fonte Hermes read-only.',
  'client_hermes_clfa',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  87200,
  'EUR',
  'extracted',
  'c469d15158ef27080601e575b0359e6298bbb7eb3e2f6b1414641517e0921ec2',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"CLFA","status":"Attivo","invoiceCount":1,"revenueCents":87200,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"B"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_colr',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:COLR',
  NULL,
  'Comparin Lorena - scheda cliente Hermes',
  'Cliente Comparin Lorena: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_colr',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  'd23e21779ac38560a0099128d1585d51ebdb150004bda71d1fce98ba70f443ea',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"COLR","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_daen',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:DAEN',
  NULL,
  'Damia Entertainment - scheda cliente Hermes',
  'Cliente Damia Entertainment: stato Inattivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_daen',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '05fb1dcf6636faa690db169befa3632329ac91c8d5c2134392c5e180d7be39fc',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"DAEN","status":"Inattivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_dejo',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:DEJO',
  NULL,
  'DebeoJobs - scheda cliente Hermes',
  'Cliente DebeoJobs: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_dejo',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '607d5dbc6f33d1e1ff545b6b5e1268049ee13ca4450e14a11be26093e9cca2bc',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"DEJO","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_dico',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:DICO',
  NULL,
  'DICO Online - scheda cliente Hermes',
  'Cliente DICO Online: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_internal_dico_online',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '4b789903e9db4dd597e5b5e73e4461366dbf338ef0d6ce2e98eca2bb2f8e896e',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"DICO","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_elsr',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:ELSR',
  NULL,
  'Elite S.r.l. - scheda cliente Hermes',
  'Cliente Elite S.r.l.: stato Attivo, 7 fatture tracciate, fatturato aggregato 6649,00 €. Fonte Hermes read-only.',
  'client_hermes_elsr',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  664900,
  'EUR',
  'extracted',
  'e9b697f4dd0082b70e95939d869822714953affc7526cd362c8570a8168ad229',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"ELSR","status":"Attivo","invoiceCount":7,"revenueCents":664900,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_enco',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:ENCO',
  NULL,
  'Ennevi Costruzioni srl - scheda cliente Hermes',
  'Cliente Ennevi Costruzioni srl: stato Attivo, 1 fatture tracciate, fatturato aggregato 1400,00 €. Fonte Hermes read-only.',
  'client_hermes_enco',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  140000,
  'EUR',
  'extracted',
  'fba4a1cb2ee3244798463e6a3aed34d0658e20c0e2475077933130ee10f363ec',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"ENCO","status":"Attivo","invoiceCount":1,"revenueCents":140000,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_fanl',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:FANL',
  NULL,
  'Fleureau Axel Nicolas Leon - scheda cliente Hermes',
  'Cliente Fleureau Axel Nicolas Leon: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_fanl',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '486713582966ac596046288a8c46da15ae6dc150a52fb27f6d7ed285385f8f76',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"FANL","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_fiba',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:FIBA',
  NULL,
  'Fiba - scheda cliente Hermes',
  'Cliente Fiba: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_fiba',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '63078ce3b4f6e7f1511c96ee3cc697e955cd9919ce42a8d113e69ca9ae20035c',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"FIBA","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_fipr',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:FIPR',
  NULL,
  'Friuli Innovazione Partner - scheda cliente Hermes',
  'Cliente Friuli Innovazione Partner: stato Inattivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_fipr',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '29ff64a7a045fc23fcd852ca91517b3ffe0af547eba8f3ff4dd8788b5829576a',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"FIPR","status":"Inattivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_fium',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:FIUM',
  NULL,
  'FIUMEDICA SRL - scheda cliente Hermes',
  'Cliente FIUMEDICA SRL: stato Attivo, 4 fatture tracciate, fatturato aggregato 1494,00 €. Fonte Hermes read-only.',
  'client_hermes_fium',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  149400,
  'EUR',
  'extracted',
  '43868017c8e4749327b39a654597b8d2db54039f8e4d2359b6e294140a8aa23a',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"FIUM","status":"Attivo","invoiceCount":4,"revenueCents":149400,"hasDocx":true,"hasNarrative":true,"hasOrganic":true,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_friu',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:FRIU',
  NULL,
  'FriuliDoc - scheda cliente Hermes',
  'Cliente FriuliDoc: stato Prospect, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_friu',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '66655f409b8db1c2b15ab7cc0b8160d63913255460a51da32d04d5ced4ca6b40',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"FRIU","status":"Prospect","invoiceCount":0,"revenueCents":0,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"C"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_gden',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:GDEN',
  NULL,
  'Gruppo Distribuzione Energia Srl - scheda cliente Hermes',
  'Cliente Gruppo Distribuzione Energia Srl: stato Attivo, 2 fatture tracciate, fatturato aggregato 1330,00 €. Fonte Hermes read-only.',
  'client_hermes_gden',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  133000,
  'EUR',
  'extracted',
  'a618a066efab90a620987457d06cdbab722f7845ca587c40566b74b8bb7ebd7f',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"GDEN","status":"Attivo","invoiceCount":2,"revenueCents":133000,"hasDocx":false,"hasNarrative":false,"hasOrganic":true,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_gmam',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:GMAM',
  NULL,
  'GM Ambiente - scheda cliente Hermes',
  'Cliente GM Ambiente: stato Attivo, 3 fatture tracciate, fatturato aggregato 2910,00 €. Fonte Hermes read-only.',
  'client_hermes_gmam',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  291000,
  'EUR',
  'extracted',
  'a83d0230eafbd1420845068e3d07438f2f9f65a3f627fefff75c463745994755',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"GMAM","status":"Attivo","invoiceCount":3,"revenueCents":291000,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_idmi',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:IDMI',
  NULL,
  'Ippodromo di Merano - scheda cliente Hermes',
  'Cliente Ippodromo di Merano: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_idmi',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '62d72bb96ab9fd8a4a0f4026e910b9062c8af34b22e65ca60b7354a2bf08b2d9',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"IDMI","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_lvlp',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:LVLP',
  NULL,
  'LVLP (Level Up) - scheda cliente Hermes',
  'Cliente LVLP (Level Up): stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_lvlp',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '6d7d0dc416e8751910c86b84592be3d3463fdc3fccbeb807b5acbba3fa31442c',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"LVLP","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_maro',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:MARO',
  NULL,
  'MASCAZZINI ROBERTO - scheda cliente Hermes',
  'Cliente MASCAZZINI ROBERTO: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_maro',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '2cc13c4abc3001fa81e7d9410fd635a207840c33aa23b602c80a26ab65d84eab',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"MARO","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_maza',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:MAZA',
  NULL,
  'Broker Motors e Velvet motors - scheda cliente Hermes',
  'Cliente Broker Motors e Velvet motors: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_maza',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '905fcb570c663895f9621e023798cb3b1b8d8d4e665d437356e4668c3d350de0',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"MAZA","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":true,"hasNarrative":true,"hasOrganic":true,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_micc',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:MICC',
  NULL,
  'Micco''s - scheda cliente Hermes',
  'Cliente Micco''s: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_micc',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '9f09ea32998b81f610c56f3dbbba2b250a95b922a6f07a8f17d78b2fb5e20159',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"MICC","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_naco',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:NACO',
  NULL,
  'Nadia Costruzioni - scheda cliente Hermes',
  'Cliente Nadia Costruzioni: stato Prospect, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_naco',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  'fff3f9fe435aee59643ce1de2ebe66f704672ea2f9e467a416d0c2fea48f4781',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"NACO","status":"Prospect","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"C"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_noic',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:NOIC',
  NULL,
  'NoiClub - scheda cliente Hermes',
  'Cliente NoiClub: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_noic',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '4a5dc44e05497b5f8a30be011ac08e4bc01175da40232d6d34f3326c242b1b58',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"NOIC","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_nole',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:NOLE',
  NULL,
  'Noleggiobar - scheda cliente Hermes',
  'Cliente Noleggiobar: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_nole',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '534c5963888a54e729a3fcc003d2103fb20de18a61a65d3870869bd474b490bd',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"NOLE","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_nume',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:NUME',
  NULL,
  'Numerology - scheda cliente Hermes',
  'Cliente Numerology: stato N/D, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_nume',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '02bd8ddfe14412bb49b58f899c6e325f9575874318f644f17dbe3d47e0291e28',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"NUME","status":"N/D","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_paot',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:PAOT',
  NULL,
  'PapiOnTheBeach - scheda cliente Hermes',
  'Cliente PapiOnTheBeach: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_paot',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  'ae7ec68008546b394d9e9dffdcd98fe7ac8c710fb2bffd8316537628e13358ed',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"PAOT","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_pnsp',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:PNSP',
  NULL,
  'PNL Sports - scheda cliente Hermes',
  'Cliente PNL Sports: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_pnsp',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '95914afe2608221d2374af40152b6a4bb158a72e302de283ba53887604a8f12e',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"PNSP","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_poco',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:POCO',
  NULL,
  'POLES COSTRUZIONI SRL - scheda cliente Hermes',
  'Cliente POLES COSTRUZIONI SRL: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_poco',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  'eff4bbd7a3f0794baba9b605e11ff8c516fd854bd07d7e59989640afce15a705',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"POCO","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_polv',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:POLV',
  NULL,
  'Tenuta Polvaro s.a.s. di De Zan Caterina & C. - scheda cliente Hermes',
  'Cliente Tenuta Polvaro s.a.s. di De Zan Caterina & C.: stato Attivo, 1 fatture tracciate, fatturato aggregato 300,00 €. Fonte Hermes read-only.',
  'client_hermes_polv',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  30000,
  'EUR',
  'extracted',
  '80a6ec79d5ecb1a856a573007b19391e9a5c68d5d9b0af67af728abe043cad5f',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"POLV","status":"Attivo","invoiceCount":1,"revenueCents":30000,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_ppap',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:PPAP',
  NULL,
  'Portopiccolo Apartments - scheda cliente Hermes',
  'Cliente Portopiccolo Apartments: stato Attivo, 1 fatture tracciate, fatturato aggregato 2750,00 €. Fonte Hermes read-only.',
  'client_rig_ppap',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  275000,
  'EUR',
  'extracted',
  '7482747a8647ce537b9f428d55ebf02980f511891d08e1bf411b164c303d587e',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"PPAP","status":"Attivo","invoiceCount":1,"revenueCents":275000,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_pusa',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:PUSA',
  NULL,
  'Punto Salute - scheda cliente Hermes',
  'Cliente Punto Salute: stato Inattivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_pusa',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '4ff8a9352f0872730474bcb89f90f00dd4f2abd15f1841a855c079f16ef71f91',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"PUSA","status":"Inattivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_rbin',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:RBIN',
  NULL,
  'RB Interior - scheda cliente Hermes',
  'Cliente RB Interior: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_rbin',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '7a9ef486a99ffb17671206941fab0fa89d318dd3f214dc5498aaee5d8c89b92c',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"RBIN","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_reca',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:RECA',
  NULL,
  'Reguta Cantina / Anselmi - scheda cliente Hermes',
  'Cliente Reguta Cantina / Anselmi: stato Attivo, 14 fatture tracciate, fatturato aggregato 23.247,22 €. Fonte Hermes read-only.',
  'client_rig_reca',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  2324722,
  'EUR',
  'extracted',
  'a8c3ab4037884dedd6761d6f506f10d3c36f20fc46bf6edc8e16f7c24f2042bf',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"RECA","status":"Attivo","invoiceCount":14,"revenueCents":2324722,"hasDocx":true,"hasNarrative":true,"hasOrganic":true,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_resr',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:RESR',
  NULL,
  'Reginato s.r.l. - scheda cliente Hermes',
  'Cliente Reginato s.r.l.: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_resr',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '1e8b8c0ecd4cc5cadba7947aac06e058a2d3b6a06c47a1bcaf73313f6b7623b1',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"RESR","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_ricg',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:RICG',
  NULL,
  'Ricci group - scheda cliente Hermes',
  'Cliente Ricci group: stato Attivo, 5 fatture tracciate, fatturato aggregato 2000,00 €. Fonte Hermes read-only.',
  'client_hermes_ricg',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  200000,
  'EUR',
  'extracted',
  'f858753099ad2e07e9caa70946f359dd34b467c305be180a71624ad929b67eb5',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"RICG","status":"Attivo","invoiceCount":5,"revenueCents":200000,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_rore',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:RORE',
  NULL,
  'Roj''z Restaurant - scheda cliente Hermes',
  'Cliente Roj''z Restaurant: stato Prospect, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_rore',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '1630ade918955b49ca26a86e484bde3f4a7809944ec0dc387997802492b083eb',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"RORE","status":"Prospect","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"C"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_sisp',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:SISP',
  NULL,
  'SCUOLA ITALIANA DI SCI PIANCAVALLO S.S. - scheda cliente Hermes',
  'Cliente SCUOLA ITALIANA DI SCI PIANCAVALLO S.S.: stato Attivo, 10 fatture tracciate, fatturato aggregato 5267,14 €. Fonte Hermes read-only.',
  'client_hermes_sisp',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  526714,
  'EUR',
  'extracted',
  '03b4cf0782e773decb7356226834c6400ebf8ae3a66aa30c0cab1330ade1dcdc',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"SISP","status":"Attivo","invoiceCount":10,"revenueCents":526714,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_spes',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:SPES',
  NULL,
  'Spesa - scheda cliente Hermes',
  'Cliente Spesa: stato Prospect, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_spes',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  'b7075587c30f1be1e8e53d898fb4308d9e743f77202e68b6e75011daa365270c',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"SPES","status":"Prospect","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"C"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_ssvo',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:SSVO',
  NULL,
  'APOLLO 2000 SRL (Solero Sport Village) - scheda cliente Hermes',
  'Cliente APOLLO 2000 SRL (Solero Sport Village): stato Attivo, 16 fatture tracciate, fatturato aggregato 5800,00 €. Fonte Hermes read-only.',
  'client_rig_ssvo',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  580000,
  'EUR',
  'extracted',
  '3d01ec30ea60a2870b0bc753e05c51ac0c45c84cf777f40225476769b7dc7d93',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"SSVO","status":"Attivo","invoiceCount":16,"revenueCents":580000,"hasDocx":true,"hasNarrative":true,"hasOrganic":true,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_stsa',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:STSA',
  NULL,
  'Studio Sancassiani - scheda cliente Hermes',
  'Cliente Studio Sancassiani: stato Prospect, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_stsa',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  'f9afc142b39dfd3be2e37c49bf2085d84c5a42df9b4d8e542523d40109ba7fdf',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"STSA","status":"Prospect","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"C"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_sywe',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:SYWE',
  NULL,
  'Synergy Wellness - scheda cliente Hermes',
  'Cliente Synergy Wellness: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_sywe',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '24fa05f2dbb111b98dbd6a91ecb4f708f25bb2d7dcad0fa5f1c1c1d5c5849db2',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"SYWE","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_tasr',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:TASR',
  NULL,
  'Talentware S.r.l. - scheda cliente Hermes',
  'Cliente Talentware S.r.l.: stato Attivo, 1 fatture tracciate, fatturato aggregato 469,00 €. Fonte Hermes read-only.',
  'client_hermes_tasr',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  46900,
  'EUR',
  'extracted',
  '9e52223eae5bc864f06eebffdfe4d33aa7cad9b84bdaeae4ae09101ce33adff9',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"TASR","status":"Attivo","invoiceCount":1,"revenueCents":46900,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"B"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_tili',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:TILI',
  NULL,
  'ThinkInk Lignano - scheda cliente Hermes',
  'Cliente ThinkInk Lignano: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_tili',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '4dbcb96323fe1c6d0432ce6dfe106832758201cdf217d31f6654179a1baf5da3',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"TILI","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_tmsl',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:TMSL',
  NULL,
  'Tomasella srl - scheda cliente Hermes',
  'Cliente Tomasella srl: stato Attivo, 4 fatture tracciate, fatturato aggregato 1988,00 €. Fonte Hermes read-only.',
  'client_hermes_tmsl',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  198800,
  'EUR',
  'extracted',
  'ae8b880461bf53cb87af6feb2ffcf51cefd70eac571ff56cd59346eea312d6c1',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"TMSL","status":"Attivo","invoiceCount":4,"revenueCents":198800,"hasDocx":true,"hasNarrative":true,"hasOrganic":true,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_tuco',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:TUCO',
  NULL,
  'Tubaro & Co - scheda cliente Hermes',
  'Cliente Tubaro & Co: stato Attivo, 2 fatture tracciate, fatturato aggregato 845,00 €. Fonte Hermes read-only.',
  'client_hermes_tuco',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  84500,
  'EUR',
  'extracted',
  '3b64ddcf5323558a5df2c03768150f252b52654d2bbd9cf10a3b65eb61f6de7a',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"TUCO","status":"Attivo","invoiceCount":2,"revenueCents":84500,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_vico',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:VICO',
  NULL,
  'Vivila così - scheda cliente Hermes',
  'Cliente Vivila così: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_vico',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '96130d7eb3a412e1eba0a4a5b812bcc60b1492afb49539eaaed75fbb08d351ae',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"VICO","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_viva',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:VIVA',
  NULL,
  'VIVARADIO SRL - scheda cliente Hermes',
  'Cliente VIVARADIO SRL: stato Attivo, 5 fatture tracciate, fatturato aggregato 1850,00 €. Fonte Hermes read-only.',
  'client_hermes_viva',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  185000,
  'EUR',
  'extracted',
  'f5535cb63d40e929f3b00b5a254d5088bc482fab99f9600431eddd67f6bbd113',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"VIVA","status":"Attivo","invoiceCount":5,"revenueCents":185000,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"A"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_vtsr',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:VTSR',
  NULL,
  'VRT SERVIZI SRL - scheda cliente Hermes',
  'Cliente VRT SERVIZI SRL: stato Attivo, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_vtsr',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  'bcac103cb1900b4a296ad18bb7b5fc631b5d2dbba8f3e8c2e5a16fe75dec1ad0',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"VTSR","status":"Attivo","invoiceCount":0,"revenueCents":0,"hasDocx":false,"hasNarrative":false,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"D"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_client_zasa',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'client',
  'hermes:client-intelligence:ZASA',
  NULL,
  'ZANUTTA SPA - scheda cliente Hermes',
  'Cliente ZANUTTA SPA: stato Prospect, 0 fatture tracciate, fatturato aggregato 0,00 €. Fonte Hermes read-only.',
  'client_hermes_zasa',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  NULL,
  'EUR',
  'extracted',
  '1813cb265a9c0983d1d1ee4cd238ee8193345dabe3afe2bc41e12b0ec6a76e61',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","note":"Detailed contact fields intentionally ignored."}',
  '{"code":"ZASA","status":"Prospect","invoiceCount":0,"revenueCents":0,"hasDocx":true,"hasNarrative":true,"hasOrganic":false,"hasAds":false,"caseStudyPriority":"C"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT(organization_id, provider, external_id) DO UPDATE SET
  source_id = excluded.source_id,
  record_type = excluded.record_type,
  title = excluded.title,
  summary = excluded.summary,
  client_id = excluded.client_id,
  occurred_at = excluded.occurred_at,
  amount_cents = excluded.amount_cents,
  currency = excluded.currency,
  confidence = excluded.confidence,
  content_hash = excluded.content_hash,
  raw_json = excluded.raw_json,
  normalized_json = excluded.normalized_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO external_data_records (
  id,
  organization_id,
  source_id,
  provider,
  record_type,
  external_id,
  external_url,
  title,
  summary,
  client_id,
  project_id,
  task_id,
  quote_id,
  interaction_id,
  occurred_at,
  amount_cents,
  currency,
  confidence,
  content_hash,
  raw_json,
  normalized_json,
  created_at,
  updated_at
) VALUES
(
  'extrec_hermes_revenue_3rtc',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:3RTC:revenue',
  NULL,
  '3R-TECHNOLOGY DI MANZAN PAOLO - fatturato tracciato Hermes',
  'Hermes riporta 3 fatture e fatturato aggregato 1950,00 € per 3R-TECHNOLOGY DI MANZAN PAOLO. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_hermes_3rtc',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  195000,
  'EUR',
  'extracted',
  '7be2d51b5dfee5292c68f21acc1639224ce6f15c3c1c75e9c5832df54cd00b7a',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"3RTC","clientName":"3R-TECHNOLOGY DI MANZAN PAOLO","invoiceCount":3,"revenueCents":195000,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_alsr',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:ALSR:revenue',
  NULL,
  'Alma S.r.l. - fatturato tracciato Hermes',
  'Hermes riporta 1 fatture e fatturato aggregato 199,00 € per Alma S.r.l.. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_hermes_alsr',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  19900,
  'EUR',
  'extracted',
  'a9716fdbf614ed088080e91d2287ba96b3544a9a51e5e34612ad1b28d1bc5ceb',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"ALSR","clientName":"Alma S.r.l.","invoiceCount":1,"revenueCents":19900,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_blwh',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:BLWH:revenue',
  NULL,
  'BLACK AND WHITE SRLS - fatturato tracciato Hermes',
  'Hermes riporta 7 fatture e fatturato aggregato 2732,30 € per BLACK AND WHITE SRLS. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_hermes_blwh',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  273230,
  'EUR',
  'extracted',
  'f1ecca932aa921617233a808196f70632fa4cdb734dd71b63f878e7ab8a0cf49',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"BLWH","clientName":"BLACK AND WHITE SRLS","invoiceCount":7,"revenueCents":273230,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_clfa',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:CLFA:revenue',
  NULL,
  'Clara Falomo - fatturato tracciato Hermes',
  'Hermes riporta 1 fatture e fatturato aggregato 872,00 € per Clara Falomo. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_hermes_clfa',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  87200,
  'EUR',
  'extracted',
  'd0be49156c4e8cab1f398886bbc62860e54c4a213dadaaefa1ed16e176ade967',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"CLFA","clientName":"Clara Falomo","invoiceCount":1,"revenueCents":87200,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_elsr',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:ELSR:revenue',
  NULL,
  'Elite S.r.l. - fatturato tracciato Hermes',
  'Hermes riporta 7 fatture e fatturato aggregato 6649,00 € per Elite S.r.l.. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_hermes_elsr',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  664900,
  'EUR',
  'extracted',
  '515b4ba812446263d5e74f4898a326b083fe29999e70287b16534193cc78ca13',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"ELSR","clientName":"Elite S.r.l.","invoiceCount":7,"revenueCents":664900,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_enco',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:ENCO:revenue',
  NULL,
  'Ennevi Costruzioni srl - fatturato tracciato Hermes',
  'Hermes riporta 1 fatture e fatturato aggregato 1400,00 € per Ennevi Costruzioni srl. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_hermes_enco',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  140000,
  'EUR',
  'extracted',
  '37463a655ca0358d0d6023744ae987b5554e51cfe4bd97cd129a5a97d64c3077',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"ENCO","clientName":"Ennevi Costruzioni srl","invoiceCount":1,"revenueCents":140000,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_fium',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:FIUM:revenue',
  NULL,
  'FIUMEDICA SRL - fatturato tracciato Hermes',
  'Hermes riporta 4 fatture e fatturato aggregato 1494,00 € per FIUMEDICA SRL. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_hermes_fium',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  149400,
  'EUR',
  'extracted',
  '2295e54e9f8886c4474d0192d9067b6c4719c7e8458de38fc0ff7c3e72171009',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"FIUM","clientName":"FIUMEDICA SRL","invoiceCount":4,"revenueCents":149400,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_gden',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:GDEN:revenue',
  NULL,
  'Gruppo Distribuzione Energia Srl - fatturato tracciato Hermes',
  'Hermes riporta 2 fatture e fatturato aggregato 1330,00 € per Gruppo Distribuzione Energia Srl. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_hermes_gden',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  133000,
  'EUR',
  'extracted',
  '469ded26ac7855397ee15c6b18f6a238e0a02b2961143842a19ded0f4bf6bc05',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"GDEN","clientName":"Gruppo Distribuzione Energia Srl","invoiceCount":2,"revenueCents":133000,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_gmam',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:GMAM:revenue',
  NULL,
  'GM Ambiente - fatturato tracciato Hermes',
  'Hermes riporta 3 fatture e fatturato aggregato 2910,00 € per GM Ambiente. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_hermes_gmam',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  291000,
  'EUR',
  'extracted',
  '97464f2b4a40513efbb77a5fdfbddb7aac8fc7f22e80e0e460f57f49164109d5',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"GMAM","clientName":"GM Ambiente","invoiceCount":3,"revenueCents":291000,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_polv',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:POLV:revenue',
  NULL,
  'Tenuta Polvaro s.a.s. di De Zan Caterina & C. - fatturato tracciato Hermes',
  'Hermes riporta 1 fatture e fatturato aggregato 300,00 € per Tenuta Polvaro s.a.s. di De Zan Caterina & C.. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_hermes_polv',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  30000,
  'EUR',
  'extracted',
  '51a83cc6908ae28b4726090d77d4b282a3218cd4c217532bb3c265614a6a79c1',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"POLV","clientName":"Tenuta Polvaro s.a.s. di De Zan Caterina & C.","invoiceCount":1,"revenueCents":30000,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_ppap',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:PPAP:revenue',
  NULL,
  'Portopiccolo Apartments - fatturato tracciato Hermes',
  'Hermes riporta 1 fatture e fatturato aggregato 2750,00 € per Portopiccolo Apartments. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_rig_ppap',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  275000,
  'EUR',
  'extracted',
  'f87a9528fddb6b31b0fb0f04eb64aab493aab5aa061c63f5a1774a553b4ccdf7',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"PPAP","clientName":"Portopiccolo Apartments","invoiceCount":1,"revenueCents":275000,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_reca',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:RECA:revenue',
  NULL,
  'Reguta Cantina / Anselmi - fatturato tracciato Hermes',
  'Hermes riporta 14 fatture e fatturato aggregato 23.247,22 € per Reguta Cantina / Anselmi. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_rig_reca',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  2324722,
  'EUR',
  'extracted',
  'a3a81192d3ce5ac0c658a1b425019f73d0379b0d90c569238c558992f14fabb6',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"RECA","clientName":"Reguta Cantina / Anselmi","invoiceCount":14,"revenueCents":2324722,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_ricg',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:RICG:revenue',
  NULL,
  'Ricci group - fatturato tracciato Hermes',
  'Hermes riporta 5 fatture e fatturato aggregato 2000,00 € per Ricci group. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_hermes_ricg',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  200000,
  'EUR',
  'extracted',
  '997f6a37d5800cc1e1679beda3eaa34d951bb5e71b2de5ca4da930ff1969d9d4',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"RICG","clientName":"Ricci group","invoiceCount":5,"revenueCents":200000,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_sisp',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:SISP:revenue',
  NULL,
  'SCUOLA ITALIANA DI SCI PIANCAVALLO S.S. - fatturato tracciato Hermes',
  'Hermes riporta 10 fatture e fatturato aggregato 5267,14 € per SCUOLA ITALIANA DI SCI PIANCAVALLO S.S.. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_hermes_sisp',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  526714,
  'EUR',
  'extracted',
  '387b571ab368904587d4ed50e47a785c61afa99e72c3311ac9ada112d96d06ae',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"SISP","clientName":"SCUOLA ITALIANA DI SCI PIANCAVALLO S.S.","invoiceCount":10,"revenueCents":526714,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_ssvo',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:SSVO:revenue',
  NULL,
  'APOLLO 2000 SRL (Solero Sport Village) - fatturato tracciato Hermes',
  'Hermes riporta 16 fatture e fatturato aggregato 5800,00 € per APOLLO 2000 SRL (Solero Sport Village). Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_rig_ssvo',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  580000,
  'EUR',
  'extracted',
  '373f24377d214b4e01b7a6a7a6771252617054c5bcb99d43ff4ba6eaa5da67a1',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"SSVO","clientName":"APOLLO 2000 SRL (Solero Sport Village)","invoiceCount":16,"revenueCents":580000,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_tasr',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:TASR:revenue',
  NULL,
  'Talentware S.r.l. - fatturato tracciato Hermes',
  'Hermes riporta 1 fatture e fatturato aggregato 469,00 € per Talentware S.r.l.. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_hermes_tasr',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  46900,
  'EUR',
  'extracted',
  'f80431932401378e756e1a98d6ce2107754228064665ee42a2f61441b8d01806',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"TASR","clientName":"Talentware S.r.l.","invoiceCount":1,"revenueCents":46900,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_tmsl',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:TMSL:revenue',
  NULL,
  'Tomasella srl - fatturato tracciato Hermes',
  'Hermes riporta 4 fatture e fatturato aggregato 1988,00 € per Tomasella srl. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_hermes_tmsl',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  198800,
  'EUR',
  'extracted',
  '2cd174ebecb75b6361077f5eacfb40e3f0ccc52d8f37f5206ea1c28e56d242f7',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"TMSL","clientName":"Tomasella srl","invoiceCount":4,"revenueCents":198800,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_tuco',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:TUCO:revenue',
  NULL,
  'Tubaro & Co - fatturato tracciato Hermes',
  'Hermes riporta 2 fatture e fatturato aggregato 845,00 € per Tubaro & Co. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_hermes_tuco',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  84500,
  'EUR',
  'extracted',
  '45e13ee50164ef180ed557b930cfbe9150b2279d5b052dd29ed22a24c6d3ad76',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"TUCO","clientName":"Tubaro & Co","invoiceCount":2,"revenueCents":84500,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'extrec_hermes_revenue_viva',
  'org_demo_righello',
  'extsrc_hermes_client_intelligence_master',
  'hermes',
  'payment',
  'hermes:client-intelligence:VIVA:revenue',
  NULL,
  'VIVARADIO SRL - fatturato tracciato Hermes',
  'Hermes riporta 5 fatture e fatturato aggregato 1850,00 € per VIVARADIO SRL. Trattare come dato amministrativo aggregato da verificare, non come singolo pagamento.',
  'client_hermes_viva',
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-04T12:15:00.000Z',
  185000,
  'EUR',
  'extracted',
  '2a348a44ecccfa4f7d15b047effb2ad0624cfe6ac137a7ce5f1eb70ddda38d37',
  '{"redacted":true,"source":"Hermes Obsidian Righello Client Intelligence Master","importedFrom":"Indice Clienti","paymentProof":false,"invoiceAggregate":true}',
  '{"code":"VIVA","clientName":"VIVARADIO SRL","invoiceCount":5,"revenueCents":185000,"currency":"EUR","evidence":"aggregated_invoice_revenue_from_hermes_master"}',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT(organization_id, provider, external_id) DO UPDATE SET
  source_id = excluded.source_id,
  record_type = excluded.record_type,
  title = excluded.title,
  summary = excluded.summary,
  client_id = excluded.client_id,
  occurred_at = excluded.occurred_at,
  amount_cents = excluded.amount_cents,
  currency = excluded.currency,
  confidence = excluded.confidence,
  content_hash = excluded.content_hash,
  raw_json = excluded.raw_json,
  normalized_json = excluded.normalized_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO audit_logs (id, organization_id, actor_member_id, action, entity_type, entity_id, metadata_json, created_at)
VALUES (
  'audit_hermes_client_intelligence_import_20260615',
  'org_demo_righello',
  'mem_axel_wearerighello',
  'import_hermes_client_intelligence',
  'external_data_source',
  'extsrc_hermes_client_intelligence_master',
  '{"rows":57,"revenueRecords":19,"sourceFile":"righello-client-intelligence-master.md","policy":"read_only_redacted"}',
  CURRENT_TIMESTAMP
) ON CONFLICT(id) DO NOTHING;
